apiVersion: v1
kind: Namespace
metadata:
  name: signoz-operator-system
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-operator
    control-plane: controller-manager
