ARG DISTROLESS_SHA="pass-a-valid-docker-sha-otherwise-this-will-fail"

FROM gcr.io/distroless/static@sha256:${DISTROLESS_SHA}
LABEL maintainer="signoz"
WORKDIR /

ARG OS="linux"
ARG ARCH

COPY ./target/${OS}-${ARCH}/signoz-operator /manager
USER 65532:65532

ENTRYPOINT ["/manager"]
