apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: signoz-operator
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-operator
roleRef:
  name: signoz-operator
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: signoz-operator
  namespace: system
  kind: ServiceAccount
