apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: signoz-operator-leader-election
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-operator
rules:
- resources:
  - configmaps
  apiGroups:
  - ""
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- resources:
  - leases
  apiGroups:
  - coordination.k8s.io
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- resources:
  - events
  apiGroups:
  - ""
  verbs:
  - create
  - patch
