// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const plannedMaintenanceCollectionPath = "/api/v1/downtime_schedules"

var (
	_ resources.Object = &PlannedMaintenanceObject{}
)

type PlannedMaintenanceObject struct {
	PlannedMaintenance *v1alpha1.PlannedMaintenance
}

func (p *PlannedMaintenanceObject) K8sObject() client.Object {
	return p.PlannedMaintenance
}

func (p *PlannedMaintenanceObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &p.PlannedMaintenance.Spec.CoreSpec
}

func (p *PlannedMaintenanceObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &p.PlannedMaintenance.Status.CoreStatus
}

func (p *PlannedMaintenanceObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(p.PlannedMaintenance.Spec.ObjectTemplate.Spec, p.PlannedMaintenance.Spec.ObjectTemplate.JSONSpec)
}

func (p *PlannedMaintenanceObject) Identity() (string, error) {
	return jsonbody.ExtractFromSpecs(p.PlannedMaintenance.Spec.ObjectTemplate.Spec, p.PlannedMaintenance.Spec.ObjectTemplate.JSONSpec, "name")
}

func (p *PlannedMaintenanceObject) Hash() (string, error) {
	body, err := p.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (p *PlannedMaintenanceObject) UpdatableFields() []string {
	return []string{"alertIds", "description", "name", "schedule", "scope"}
}

func (p *PlannedMaintenanceObject) ImmutableFields() []string {
	return []string{}
}

func (p *PlannedMaintenanceObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (p *PlannedMaintenanceObject) ToUpdate() (json.RawMessage, error) {
	body, err := p.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, p.UpdatableFields())
}

func (p *PlannedMaintenanceObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := p.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	paths := jsonbody.Diff(gjson.ParseBytes(body).Value(), gjson.GetBytes(response, "data").Value())

	return resources.CompareResult{
		UpdatableFields: jsonbody.Intersect(paths, p.UpdatableFields()),
		ImmutableFields: jsonbody.Intersect(paths, p.ImmutableFields()),
	}, nil
}

func (p *PlannedMaintenanceObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, plannedMaintenanceCollectionPath
}

func (p *PlannedMaintenanceObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, plannedMaintenanceCollectionPath + "/" + id
}

func (p *PlannedMaintenanceObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, plannedMaintenanceCollectionPath + "/" + id
}

func (p *PlannedMaintenanceObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, plannedMaintenanceCollectionPath + "/" + id
}
