// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const serviceAccountCollectionPath = "/api/v1/service_accounts"

var (
	_ resources.Object = &ServiceAccountObject{}
)

type ServiceAccountObject struct {
	ServiceAccount *v1alpha1.ServiceAccount
}

func (s *ServiceAccountObject) K8sObject() client.Object {
	return s.ServiceAccount
}

func (s *ServiceAccountObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &s.ServiceAccount.Spec.CoreSpec
}

func (s *ServiceAccountObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &s.ServiceAccount.Status.CoreStatus
}

func (s *ServiceAccountObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(s.ServiceAccount.Spec.ObjectTemplate.Spec, s.ServiceAccount.Spec.ObjectTemplate.JSONSpec)
}

func (s *ServiceAccountObject) Identity() (string, error) {
	return jsonbody.ExtractFromSpecs(s.ServiceAccount.Spec.ObjectTemplate.Spec, s.ServiceAccount.Spec.ObjectTemplate.JSONSpec, "name")
}

func (s *ServiceAccountObject) Hash() (string, error) {
	body, err := s.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (s *ServiceAccountObject) UpdatableFields() []string {
	return []string{"name"}
}

func (s *ServiceAccountObject) ImmutableFields() []string {
	return []string{}
}

func (s *ServiceAccountObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (s *ServiceAccountObject) ToUpdate() (json.RawMessage, error) {
	body, err := s.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, s.UpdatableFields())
}

func (s *ServiceAccountObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := s.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	paths := jsonbody.Diff(gjson.ParseBytes(body).Value(), gjson.GetBytes(response, "data").Value())

	return resources.CompareResult{
		UpdatableFields: jsonbody.Intersect(paths, s.UpdatableFields()),
		ImmutableFields: jsonbody.Intersect(paths, s.ImmutableFields()),
	}, nil
}

func (s *ServiceAccountObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, serviceAccountCollectionPath
}

func (s *ServiceAccountObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, serviceAccountCollectionPath + "/" + id
}

func (s *ServiceAccountObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, serviceAccountCollectionPath + "/" + id
}

func (s *ServiceAccountObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, serviceAccountCollectionPath + "/" + id
}
