// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const dashboardCollectionPath = "/api/v2/dashboards"

var (
	_ resources.Object = &DashboardObject{}
)

type DashboardObject struct {
	Dashboard *v1alpha1.Dashboard
}

func (d *DashboardObject) K8sObject() client.Object {
	return d.Dashboard
}

func (d *DashboardObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &d.Dashboard.Spec.CoreSpec
}

func (d *DashboardObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &d.Dashboard.Status.CoreStatus
}

func (d *DashboardObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(d.Dashboard.Spec.ObjectTemplate.Spec, d.Dashboard.Spec.ObjectTemplate.JSONSpec)
}

func (d *DashboardObject) Identity() (string, error) {
	return jsonbody.ExtractFromSpecs(d.Dashboard.Spec.ObjectTemplate.Spec, d.Dashboard.Spec.ObjectTemplate.JSONSpec, "name")
}

func (d *DashboardObject) Hash() (string, error) {
	body, err := d.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (d *DashboardObject) UpdatableFields() []string {
	return []string{"image", "name", "schemaVersion", "spec", "tags"}
}

func (d *DashboardObject) ImmutableFields() []string {
	return []string{}
}

func (d *DashboardObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (d *DashboardObject) ToUpdate() (json.RawMessage, error) {
	body, err := d.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, d.UpdatableFields())
}

func (d *DashboardObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := d.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	paths := jsonbody.Diff(gjson.ParseBytes(body).Value(), gjson.GetBytes(response, "data").Value())

	return resources.CompareResult{
		UpdatableFields: jsonbody.Intersect(paths, d.UpdatableFields()),
		ImmutableFields: jsonbody.Intersect(paths, d.ImmutableFields()),
	}, nil
}

func (d *DashboardObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, dashboardCollectionPath
}

func (d *DashboardObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, dashboardCollectionPath + "/" + id
}

func (d *DashboardObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, dashboardCollectionPath + "/" + id
}

func (d *DashboardObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, dashboardCollectionPath + "/" + id
}
