// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const routePolicyCollectionPath = "/api/v1/route_policies"

var (
	_ resources.Object = &RoutePolicyObject{}
)

type RoutePolicyObject struct {
	RoutePolicy *v1alpha1.RoutePolicy
}

func (r *RoutePolicyObject) K8sObject() client.Object {
	return r.RoutePolicy
}

func (r *RoutePolicyObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &r.RoutePolicy.Spec.CoreSpec
}

func (r *RoutePolicyObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &r.RoutePolicy.Status.CoreStatus
}

func (r *RoutePolicyObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(r.RoutePolicy.Spec.ObjectTemplate.Spec, r.RoutePolicy.Spec.ObjectTemplate.JSONSpec)
}

func (r *RoutePolicyObject) Identity() (string, error) {
	return jsonbody.ExtractFromSpecs(r.RoutePolicy.Spec.ObjectTemplate.Spec, r.RoutePolicy.Spec.ObjectTemplate.JSONSpec, "name")
}

func (r *RoutePolicyObject) Hash() (string, error) {
	body, err := r.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (r *RoutePolicyObject) UpdatableFields() []string {
	return []string{"channels", "description", "expression", "kind", "name", "tags"}
}

func (r *RoutePolicyObject) ImmutableFields() []string {
	return []string{}
}

func (r *RoutePolicyObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (r *RoutePolicyObject) ToUpdate() (json.RawMessage, error) {
	body, err := r.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, r.UpdatableFields())
}

func (r *RoutePolicyObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := r.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	paths := jsonbody.Diff(gjson.ParseBytes(body).Value(), gjson.GetBytes(response, "data").Value())

	return resources.CompareResult{
		UpdatableFields: jsonbody.Intersect(paths, r.UpdatableFields()),
		ImmutableFields: jsonbody.Intersect(paths, r.ImmutableFields()),
	}, nil
}

func (r *RoutePolicyObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, routePolicyCollectionPath
}

func (r *RoutePolicyObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, routePolicyCollectionPath + "/" + id
}

func (r *RoutePolicyObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, routePolicyCollectionPath + "/" + id
}

func (r *RoutePolicyObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, routePolicyCollectionPath + "/" + id
}
