// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const roleCollectionPath = "/api/v1/roles"

var (
	_ resources.Object = &RoleObject{}
)

type RoleObject struct {
	Role *v1alpha1.Role
}

func (r *RoleObject) K8sObject() client.Object {
	return r.Role
}

func (r *RoleObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &r.Role.Spec.CoreSpec
}

func (r *RoleObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &r.Role.Status.CoreStatus
}

func (r *RoleObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(r.Role.Spec.ObjectTemplate.Spec, r.Role.Spec.ObjectTemplate.JSONSpec)
}

func (r *RoleObject) Identity() (string, error) {
	return jsonbody.ExtractFromSpecs(r.Role.Spec.ObjectTemplate.Spec, r.Role.Spec.ObjectTemplate.JSONSpec, "name")
}

func (r *RoleObject) Hash() (string, error) {
	body, err := r.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (r *RoleObject) UpdatableFields() []string {
	return []string{"description", "transactionGroups"}
}

func (r *RoleObject) ImmutableFields() []string {
	return []string{"name"}
}

func (r *RoleObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (r *RoleObject) ToUpdate() (json.RawMessage, error) {
	body, err := r.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, r.UpdatableFields())
}

func (r *RoleObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := r.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	paths := jsonbody.Diff(gjson.ParseBytes(body).Value(), gjson.GetBytes(response, "data").Value())

	return resources.CompareResult{
		UpdatableFields: jsonbody.Intersect(paths, r.UpdatableFields()),
		ImmutableFields: jsonbody.Intersect(paths, r.ImmutableFields()),
	}, nil
}

func (r *RoleObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, roleCollectionPath
}

func (r *RoleObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, roleCollectionPath + "/" + id
}

func (r *RoleObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, roleCollectionPath + "/" + id
}

func (r *RoleObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, roleCollectionPath + "/" + id
}
