// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const ruleCollectionPath = "/api/v2/rules"

var (
	_ resources.Object = &RuleObject{}
)

type RuleObject struct {
	Rule *v1alpha1.Rule
}

func (r *RuleObject) K8sObject() client.Object {
	return r.Rule
}

func (r *RuleObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &r.Rule.Spec.CoreSpec
}

func (r *RuleObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &r.Rule.Status.CoreStatus
}

func (r *RuleObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(r.Rule.Spec.ObjectTemplate.Spec, r.Rule.Spec.ObjectTemplate.JSONSpec)
}

func (r *RuleObject) Identity() (string, error) {
	return jsonbody.ExtractFromSpecs(r.Rule.Spec.ObjectTemplate.Spec, r.Rule.Spec.ObjectTemplate.JSONSpec, "alert")
}

func (r *RuleObject) Hash() (string, error) {
	body, err := r.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (r *RuleObject) UpdatableFields() []string {
	return []string{"alert", "alertType", "annotations", "condition", "description", "disabled", "evaluation", "labels", "notificationSettings", "ruleType", "schemaVersion"}
}

func (r *RuleObject) ImmutableFields() []string {
	return []string{}
}

func (r *RuleObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (r *RuleObject) ToUpdate() (json.RawMessage, error) {
	body, err := r.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, r.UpdatableFields())
}

func (r *RuleObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := r.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	paths := jsonbody.Diff(gjson.ParseBytes(body).Value(), gjson.GetBytes(response, "data").Value())

	return resources.CompareResult{
		UpdatableFields: jsonbody.Intersect(paths, r.UpdatableFields()),
		ImmutableFields: jsonbody.Intersect(paths, r.ImmutableFields()),
	}, nil
}

func (r *RuleObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, ruleCollectionPath
}

func (r *RuleObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, ruleCollectionPath + "/" + id
}

func (r *RuleObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, ruleCollectionPath + "/" + id
}

func (r *RuleObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, ruleCollectionPath + "/" + id
}
