// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const authDomainCollectionPath = "/api/v2/auth_domains"

var (
	_ resources.Object = &AuthDomainObject{}
)

type AuthDomainObject struct {
	AuthDomain *v1alpha1.AuthDomain
}

func (a *AuthDomainObject) K8sObject() client.Object {
	return a.AuthDomain
}

func (a *AuthDomainObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &a.AuthDomain.Spec.CoreSpec
}

func (a *AuthDomainObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &a.AuthDomain.Status.CoreStatus
}

func (a *AuthDomainObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(a.AuthDomain.Spec.ObjectTemplate.Spec, a.AuthDomain.Spec.ObjectTemplate.JSONSpec)
}

func (a *AuthDomainObject) Identity() (string, error) {
	template := a.AuthDomain.Spec.ObjectTemplate

	switch {
	case template.Spec != nil:
		return template.Spec.Name, nil
	case template.JSONSpec != nil:
		body, err := jsonbody.Extract[struct {
			Name string `json:"name"`
		}](*template.JSONSpec)
		if err != nil {
			return "", fmt.Errorf("objectTemplate.jsonSpec: %w", err)
		}

		return body.Name, nil
	default:
		return "", errors.New("objectTemplate: exactly one of spec or jsonSpec must be set")
	}
}

func (a *AuthDomainObject) Hash() (string, error) {
	body, err := a.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (a *AuthDomainObject) UpdatableFields() []string {
	return []string{"config", "enabled", "roleMapping"}
}

func (a *AuthDomainObject) ImmutableFields() []string {
	return []string{"name"}
}

func (a *AuthDomainObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (a *AuthDomainObject) ToUpdate() (json.RawMessage, error) {
	body, err := a.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, a.UpdatableFields())
}

func (a *AuthDomainObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := a.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	diff := jsonbody.DiffWithFields(body, json.RawMessage(gjson.GetBytes(response, "data").Raw), a.UpdatableFields(), a.ImmutableFields())

	return resources.CompareResult{
		UpdatableFields: diff.Updatable,
		ImmutableFields: diff.Immutable,
	}, nil
}

func (a *AuthDomainObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, authDomainCollectionPath
}

func (a *AuthDomainObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, authDomainCollectionPath + "/" + id
}

func (a *AuthDomainObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, authDomainCollectionPath + "/" + id
}

func (a *AuthDomainObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, authDomainCollectionPath + "/" + id
}
