// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"reflect"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const userCollectionPath = "/api/v2/users"

var (
	_ resources.Object = &UserObject{}
)

type UserObject struct {
	User *v1alpha1.User
}

func (u *UserObject) K8sObject() client.Object {
	return u.User
}

func (u *UserObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &u.User.Spec.CoreSpec
}

func (u *UserObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &u.User.Status.CoreStatus
}

func (u *UserObject) Body() (json.RawMessage, error) {
	return renderTemplate(u.User.Spec.ObjectTemplate.Spec, u.User.Spec.ObjectTemplate.JSONSpec)
}

func (u *UserObject) Identity() (string, error) {
	template := u.User.Spec.ObjectTemplate

	switch {
	case template.Spec != nil:
		return template.Spec.Email, nil
	case template.JSONSpec != nil:
		var body struct {
			Email string `json:"email"`
		}

		if err := json.Unmarshal([]byte(*template.JSONSpec), &body); err != nil {
			return "", fmt.Errorf("objectTemplate.jsonSpec: not valid JSON: %w", err)
		}

		return body.Email, nil
	default:
		return "", errors.New("objectTemplate: exactly one of spec or jsonSpec must be set")
	}
}

func (u *UserObject) Hash() (string, error) {
	body, err := u.Body()
	if err != nil {
		return "", err
	}

	return canonicalHash(body)
}

func (u *UserObject) UpdatableFields() []string {
	return []string{"displayName"}
}

func (u *UserObject) ImmutableFields() []string {
	return []string{"email"}
}

func (u *UserObject) ToSigNozResource(response map[string]any) (*v1alpha1.SigNozResource, error) {
	raw, err := json.Marshal(response)
	if err != nil {
		return nil, err
	}

	id := gjson.GetBytes(raw, "data.id").String()
	if id == "" {
		return nil, errors.New("response carries no id")
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (u *UserObject) ToUpdate() (json.RawMessage, error) {
	body, err := u.Body()
	if err != nil {
		return nil, err
	}

	payload := map[string]any{}

	for _, field := range u.UpdatableFields() {
		if value := gjson.GetBytes(body, field); value.Exists() {
			payload[field] = value.Value()
		}
	}

	if len(payload) == 0 {
		return nil, nil
	}

	return json.Marshal(payload)
}

func (u *UserObject) Compare(response map[string]any) (resources.CompareResult, error) {
	body, err := u.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	remote, err := json.Marshal(response)
	if err != nil {
		return resources.CompareResult{}, err
	}

	var drift resources.CompareResult

	for _, field := range u.UpdatableFields() {
		desired := gjson.GetBytes(body, field)
		if !desired.Exists() {
			continue
		}

		if !reflect.DeepEqual(desired.Value(), gjson.GetBytes(remote, "data."+field).Value()) {
			drift.UpdatableFields = append(drift.UpdatableFields, field)
		}
	}

	for _, field := range u.ImmutableFields() {
		desired := gjson.GetBytes(body, field)
		if !desired.Exists() {
			continue
		}

		value := gjson.GetBytes(remote, "data."+field)
		if !value.Exists() {
			continue
		}

		if !reflect.DeepEqual(desired.Value(), value.Value()) {
			drift.ImmutableFields = append(drift.ImmutableFields, field)
		}
	}

	return drift, nil
}

func (u *UserObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, userCollectionPath
}

func (u *UserObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodPut, pathByID(userCollectionPath, resourceMetadata)
}

func (u *UserObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodGet, pathByID(userCollectionPath, resourceMetadata)
}

func (u *UserObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodDelete, pathByID(userCollectionPath, resourceMetadata)
}
