// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const userCollectionPath = "/api/v2/users"

var (
	_ resources.Object = &UserObject{}
)

type UserObject struct {
	User *v1alpha1.User
}

func (u *UserObject) K8sObject() client.Object {
	return u.User
}

func (u *UserObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &u.User.Spec.CoreSpec
}

func (u *UserObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &u.User.Status.CoreStatus
}

func (u *UserObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(u.User.Spec.ObjectTemplate.Spec, u.User.Spec.ObjectTemplate.JSONSpec)
}

func (u *UserObject) Identity() (string, error) {
	template := u.User.Spec.ObjectTemplate

	switch {
	case template.Spec != nil:
		return template.Spec.Email, nil
	case template.JSONSpec != nil:
		body, err := jsonbody.Extract[struct {
			Email string `json:"email"`
		}](*template.JSONSpec)
		if err != nil {
			return "", fmt.Errorf("objectTemplate.jsonSpec: %w", err)
		}

		return body.Email, nil
	default:
		return "", errors.New("objectTemplate: exactly one of spec or jsonSpec must be set")
	}
}

func (u *UserObject) Hash() (string, error) {
	body, err := u.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (u *UserObject) UpdatableFields() []string {
	return []string{"displayName"}
}

func (u *UserObject) ImmutableFields() []string {
	return []string{"email"}
}

func (u *UserObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (u *UserObject) ToUpdate() (json.RawMessage, error) {
	body, err := u.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, u.UpdatableFields())
}

func (u *UserObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := u.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	diff := jsonbody.DiffWithFields(body, json.RawMessage(gjson.GetBytes(response, "data").Raw), u.UpdatableFields(), u.ImmutableFields())

	return resources.CompareResult{
		UpdatableFields: diff.Updatable,
		ImmutableFields: diff.Immutable,
	}, nil
}

func (u *UserObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, userCollectionPath
}

func (u *UserObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, userCollectionPath + "/" + id
}

func (u *UserObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, userCollectionPath + "/" + id
}

func (u *UserObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, userCollectionPath + "/" + id
}
