// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/jsonbody"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const savedViewCollectionPath = "/api/v2/saved_views"

var (
	_ resources.Object = &SavedViewObject{}
)

type SavedViewObject struct {
	SavedView *v1alpha1.SavedView
}

func (s *SavedViewObject) K8sObject() client.Object {
	return s.SavedView
}

func (s *SavedViewObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &s.SavedView.Spec.CoreSpec
}

func (s *SavedViewObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &s.SavedView.Status.CoreStatus
}

func (s *SavedViewObject) Body() (json.RawMessage, error) {
	return jsonbody.Render(s.SavedView.Spec.ObjectTemplate.Spec, s.SavedView.Spec.ObjectTemplate.JSONSpec)
}

func (s *SavedViewObject) Identity() (string, error) {
	template := s.SavedView.Spec.ObjectTemplate

	switch {
	case template.Spec != nil:
		return template.Spec.Name, nil
	case template.JSONSpec != nil:
		body, err := jsonbody.Extract[struct {
			Name string `json:"name"`
		}](*template.JSONSpec)
		if err != nil {
			return "", fmt.Errorf("objectTemplate.jsonSpec: %w", err)
		}

		return body.Name, nil
	default:
		return "", errors.New("objectTemplate: exactly one of spec or jsonSpec must be set")
	}
}

func (s *SavedViewObject) Hash() (string, error) {
	body, err := s.Body()
	if err != nil {
		return "", err
	}

	return jsonbody.Hash(body)
}

func (s *SavedViewObject) UpdatableFields() []string {
	return []string{"schemaVersion", "source", "spec"}
}

func (s *SavedViewObject) ImmutableFields() []string {
	return []string{"name"}
}

func (s *SavedViewObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	id, err := jsonbody.ExtractString(response, "data.id")
	if err != nil {
		return nil, err
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (s *SavedViewObject) ToUpdate() (json.RawMessage, error) {
	body, err := s.Body()
	if err != nil {
		return nil, err
	}

	return jsonbody.ExtractFields(body, s.UpdatableFields())
}

func (s *SavedViewObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	body, err := s.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	diff := jsonbody.DiffWithFields(body, json.RawMessage(gjson.GetBytes(response, "data").Raw), s.UpdatableFields(), s.ImmutableFields())

	return resources.CompareResult{
		UpdatableFields: diff.Updatable,
		ImmutableFields: diff.Immutable,
	}, nil
}

func (s *SavedViewObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, savedViewCollectionPath
}

func (s *SavedViewObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodPut, savedViewCollectionPath + "/" + id
}

func (s *SavedViewObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodGet, savedViewCollectionPath + "/" + id
}

func (s *SavedViewObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	id, _ := v1alpha1.GetIDFromSigNozResource(resourceMetadata)

	return http.MethodDelete, savedViewCollectionPath + "/" + id
}
