// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"reflect"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const dashboardCollectionPath = "/api/v2/dashboards"

var (
	_ resources.Object = &DashboardObject{}
)

type DashboardObject struct {
	Dashboard *v1alpha1.Dashboard
}

func (d *DashboardObject) K8sObject() client.Object {
	return d.Dashboard
}

func (d *DashboardObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &d.Dashboard.Spec.CoreSpec
}

func (d *DashboardObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &d.Dashboard.Status.CoreStatus
}

func (d *DashboardObject) Body() (json.RawMessage, error) {
	return renderTemplate(d.Dashboard.Spec.ObjectTemplate.Spec, d.Dashboard.Spec.ObjectTemplate.JSONSpec)
}

func (d *DashboardObject) Identity() (string, error) {
	template := d.Dashboard.Spec.ObjectTemplate

	switch {
	case template.Spec != nil:
		return template.Spec.Name, nil
	case template.JSONSpec != nil:
		var body struct {
			Name string `json:"name"`
		}

		if err := json.Unmarshal([]byte(*template.JSONSpec), &body); err != nil {
			return "", fmt.Errorf("objectTemplate.jsonSpec: not valid JSON: %w", err)
		}

		return body.Name, nil
	default:
		return "", errors.New("objectTemplate: exactly one of spec or jsonSpec must be set")
	}
}

func (d *DashboardObject) Hash() (string, error) {
	body, err := d.Body()
	if err != nil {
		return "", err
	}

	return canonicalHash(body)
}

func (d *DashboardObject) UpdatableFields() []string {
	return []string{"image", "name", "schemaVersion", "spec", "tags"}
}

func (d *DashboardObject) ImmutableFields() []string {
	return []string{}
}

func (d *DashboardObject) ToSigNozResource(response map[string]any) (*v1alpha1.SigNozResource, error) {
	raw, err := json.Marshal(response)
	if err != nil {
		return nil, err
	}

	id := gjson.GetBytes(raw, "data.id").String()
	if id == "" {
		return nil, errors.New("response carries no id")
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (d *DashboardObject) ToUpdate() (json.RawMessage, error) {
	body, err := d.Body()
	if err != nil {
		return nil, err
	}

	payload := map[string]any{}

	for _, field := range d.UpdatableFields() {
		if value := gjson.GetBytes(body, field); value.Exists() {
			payload[field] = value.Value()
		}
	}

	if len(payload) == 0 {
		return nil, nil
	}

	return json.Marshal(payload)
}

func (d *DashboardObject) Compare(response map[string]any) (resources.CompareResult, error) {
	body, err := d.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	remote, err := json.Marshal(response)
	if err != nil {
		return resources.CompareResult{}, err
	}

	var drift resources.CompareResult

	for _, field := range d.UpdatableFields() {
		desired := gjson.GetBytes(body, field)
		if !desired.Exists() {
			continue
		}

		if !reflect.DeepEqual(desired.Value(), gjson.GetBytes(remote, "data."+field).Value()) {
			drift.UpdatableFields = append(drift.UpdatableFields, field)
		}
	}

	for _, field := range d.ImmutableFields() {
		desired := gjson.GetBytes(body, field)
		if !desired.Exists() {
			continue
		}

		value := gjson.GetBytes(remote, "data."+field)
		if !value.Exists() {
			continue
		}

		if !reflect.DeepEqual(desired.Value(), value.Value()) {
			drift.ImmutableFields = append(drift.ImmutableFields, field)
		}
	}

	return drift, nil
}

func (d *DashboardObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, dashboardCollectionPath
}

func (d *DashboardObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodPut, pathByID(dashboardCollectionPath, resourceMetadata)
}

func (d *DashboardObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodGet, pathByID(dashboardCollectionPath, resourceMetadata)
}

func (d *DashboardObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodDelete, pathByID(dashboardCollectionPath, resourceMetadata)
}
