// Code generated by skaff operator objects DO NOT EDIT.

package objects

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"reflect"

	"github.com/tidwall/gjson"
	"sigs.k8s.io/controller-runtime/pkg/client"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/resources"
)

const savedViewCollectionPath = "/api/v2/saved_views"

var (
	_ resources.Object = &SavedViewObject{}
)

type SavedViewObject struct {
	SavedView *v1alpha1.SavedView
}

func (s *SavedViewObject) K8sObject() client.Object {
	return s.SavedView
}

func (s *SavedViewObject) GetCoreSpec() *v1alpha1.CoreSpec {
	return &s.SavedView.Spec.CoreSpec
}

func (s *SavedViewObject) GetCoreStatus() *v1alpha1.CoreStatus {
	return &s.SavedView.Status.CoreStatus
}

func (s *SavedViewObject) Body() (json.RawMessage, error) {
	return renderTemplate(s.SavedView.Spec.ObjectTemplate.Spec, s.SavedView.Spec.ObjectTemplate.JSONSpec)
}

func (s *SavedViewObject) Identity() (string, error) {
	template := s.SavedView.Spec.ObjectTemplate

	switch {
	case template.Spec != nil:
		return template.Spec.Name, nil
	case template.JSONSpec != nil:
		var body struct {
			Name string `json:"name"`
		}

		if err := json.Unmarshal([]byte(*template.JSONSpec), &body); err != nil {
			return "", fmt.Errorf("objectTemplate.jsonSpec: not valid JSON: %w", err)
		}

		return body.Name, nil
	default:
		return "", errors.New("objectTemplate: exactly one of spec or jsonSpec must be set")
	}
}

func (s *SavedViewObject) Hash() (string, error) {
	body, err := s.Body()
	if err != nil {
		return "", err
	}

	return canonicalHash(body)
}

func (s *SavedViewObject) UpdatableFields() []string {
	return []string{"schemaVersion", "source", "spec"}
}

func (s *SavedViewObject) ImmutableFields() []string {
	return []string{"name"}
}

func (s *SavedViewObject) ToSigNozResource(response map[string]any) (*v1alpha1.SigNozResource, error) {
	raw, err := json.Marshal(response)
	if err != nil {
		return nil, err
	}

	id := gjson.GetBytes(raw, "data.id").String()
	if id == "" {
		return nil, errors.New("response carries no id")
	}

	return &v1alpha1.SigNozResource{ID: &id}, nil
}

func (s *SavedViewObject) ToUpdate() (json.RawMessage, error) {
	body, err := s.Body()
	if err != nil {
		return nil, err
	}

	payload := map[string]any{}

	for _, field := range s.UpdatableFields() {
		if value := gjson.GetBytes(body, field); value.Exists() {
			payload[field] = value.Value()
		}
	}

	if len(payload) == 0 {
		return nil, nil
	}

	return json.Marshal(payload)
}

func (s *SavedViewObject) Compare(response map[string]any) (resources.CompareResult, error) {
	body, err := s.Body()
	if err != nil {
		return resources.CompareResult{}, err
	}

	remote, err := json.Marshal(response)
	if err != nil {
		return resources.CompareResult{}, err
	}

	var drift resources.CompareResult

	for _, field := range s.UpdatableFields() {
		desired := gjson.GetBytes(body, field)
		if !desired.Exists() {
			continue
		}

		if !reflect.DeepEqual(desired.Value(), gjson.GetBytes(remote, "data."+field).Value()) {
			drift.UpdatableFields = append(drift.UpdatableFields, field)
		}
	}

	for _, field := range s.ImmutableFields() {
		desired := gjson.GetBytes(body, field)
		if !desired.Exists() {
			continue
		}

		value := gjson.GetBytes(remote, "data."+field)
		if !value.Exists() {
			continue
		}

		if !reflect.DeepEqual(desired.Value(), value.Value()) {
			drift.ImmutableFields = append(drift.ImmutableFields, field)
		}
	}

	return drift, nil
}

func (s *SavedViewObject) CreateMethodAndPath() (string, string) {
	return http.MethodPost, savedViewCollectionPath
}

func (s *SavedViewObject) UpdateMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodPut, pathByID(savedViewCollectionPath, resourceMetadata)
}

func (s *SavedViewObject) ReadMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodGet, pathByID(savedViewCollectionPath, resourceMetadata)
}

func (s *SavedViewObject) DeleteMethodAndPath(resourceMetadata *v1alpha1.SigNozResource) (string, string) {
	return http.MethodDelete, pathByID(savedViewCollectionPath, resourceMetadata)
}
