// Code generated by skaff operator controllers DO NOT EDIT.
//
// Controllers are generated-only: behavior changes go into the shared helpers
// or the skaff template, then every kind is regenerated.

package resources

import (
	"context"
	"fmt"

	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	resourcesv1alpha1 "github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/resources"
	"github.com/SigNoz/signoz-operator/internal/resources/objects"
)

// UserReconciler reconciles a User object against SigNoz through
// the shared mirrored-resource engine.
type UserReconciler struct {
	client.Client
	Scheme *runtime.Scheme

	CommonReconciler resources.Reconciler
}

// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=users,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=users/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=users/finalizers,verbs=update
// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=providerconfigs,verbs=get;list;watch
// +kubebuilder:rbac:groups=resources.signoz.io,resources=clusterproviderconfigs,verbs=get;list;watch
// +kubebuilder:rbac:groups="",namespace=signoz-operator-system,resources=secrets;configmaps,verbs=get;list;watch

// Reconcile mirrors one User into SigNoz: it creates the user at
// most once, keeps its updatable fields in sync, and reclaims it on deletion
// per the reclaim policy. The control flow lives in the shared engine.
func (r *UserReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	user := &resourcesv1alpha1.User{}
	if err := r.Get(ctx, req.NamespacedName, user); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	return r.CommonReconciler.Reconcile(ctx, &objects.UserObject{User: user})
}

// SetupWithManager sets up the controller with the Manager.
func (r *UserReconciler) SetupWithManager(mgr ctrl.Manager) error {
	if err := indexProviderConfigRef(mgr, &resourcesv1alpha1.User{}, func(o client.Object) resourcesv1alpha1.ProviderConfigRef {
		return o.(*resourcesv1alpha1.User).Spec.ProviderConfigRef
	}); err != nil {
		return fmt.Errorf("could not index User provider config references: %w", err)
	}

	newList := func() client.ObjectList { return &resourcesv1alpha1.UserList{} }

	return ctrl.NewControllerManagedBy(mgr).
		For(&resourcesv1alpha1.User{}).
		Watches(&resourcesv1alpha1.ProviderConfig{}, watchProviderConfigs(r.Client, newList)).
		Watches(&resourcesv1alpha1.ClusterProviderConfig{}, watchClusterProviderConfigs(r.Client, newList)).
		Named("resources-user").
		Complete(r)
}
