// Code generated by skaff operator controllers DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"k8s.io/apimachinery/pkg/runtime"
	ctrl "sigs.k8s.io/controller-runtime"
	"sigs.k8s.io/controller-runtime/pkg/client"

	resourcesv1alpha1 "github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/resources"
	"github.com/SigNoz/signoz-operator/internal/resources/objects"
)

type SavedViewReconciler struct {
	client.Client
	Scheme *runtime.Scheme

	CommonReconciler resources.Reconciler
}

// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=savedviews,verbs=get;list;watch;create;update;patch;delete
// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=savedviews/status,verbs=get;update;patch
// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=savedviews/finalizers,verbs=update
// +kubebuilder:rbac:groups=resources.signoz.io,namespace=signoz-operator-system,resources=providerconfigs,verbs=get;list;watch
// +kubebuilder:rbac:groups=resources.signoz.io,resources=clusterproviderconfigs,verbs=get;list;watch
// +kubebuilder:rbac:groups="",namespace=signoz-operator-system,resources=secrets;configmaps,verbs=get;list;watch

func (r *SavedViewReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
	savedView := &resourcesv1alpha1.SavedView{}
	if err := r.Get(ctx, req.NamespacedName, savedView); err != nil {
		return ctrl.Result{}, client.IgnoreNotFound(err)
	}

	return r.CommonReconciler.Reconcile(ctx, &objects.SavedViewObject{SavedView: savedView})
}

func (r *SavedViewReconciler) SetupWithManager(mgr ctrl.Manager) error {
	if err := indexProviderConfigRef(mgr, &resourcesv1alpha1.SavedView{}, func(o client.Object) resourcesv1alpha1.ProviderConfigRef {
		return o.(*resourcesv1alpha1.SavedView).Spec.ProviderConfigRef
	}); err != nil {
		return fmt.Errorf("could not index SavedView provider config references: %w", err)
	}

	newList := func() client.ObjectList { return &resourcesv1alpha1.SavedViewList{} }

	return ctrl.NewControllerManagedBy(mgr).
		For(&resourcesv1alpha1.SavedView{}).
		Watches(&resourcesv1alpha1.ProviderConfig{}, watchProviderConfigs(r.Client, newList)).
		Watches(&resourcesv1alpha1.ClusterProviderConfig{}, watchClusterProviderConfigs(r.Client, newList)).
		Named("resources-savedview").
		Complete(r)
}
