apiVersion: resources.signoz.io/v1alpha1
kind: ProviderConfig
metadata:
  name: providerconfig-sample
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-operator
spec:
  auth:
    header:
      # name defaults to SIGNOZ-API-KEY
      valueFrom:
        secretKeyRef:
          name: signoz-api
          key: token
  endpoint:
    value: https://eu.signoz.cloud
