// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcestest

import (
	"context"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/clients"
	"github.com/SigNoz/signoz-operator/internal/resources"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFinder creates a new instance of MockFinder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinder {
	mock := &MockFinder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFinder is an autogenerated mock type for the Finder type
type MockFinder struct {
	mock.Mock
}

type MockFinder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinder) EXPECT() *MockFinder_Expecter {
	return &MockFinder_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockFinder
func (_mock *MockFinder) Find(ctx context.Context, c clients.SigNoz, obj resources.Object) ([]*v1alpha1.SigNozResource, error) {
	ret := _mock.Called(ctx, c, obj)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []*v1alpha1.SigNozResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object) ([]*v1alpha1.SigNozResource, error)); ok {
		return returnFunc(ctx, c, obj)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object) []*v1alpha1.SigNozResource); ok {
		r0 = returnFunc(ctx, c, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.SigNozResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clients.SigNoz, resources.Object) error); ok {
		r1 = returnFunc(ctx, c, obj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFinder_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockFinder_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - c clients.SigNoz
//   - obj resources.Object
func (_e *MockFinder_Expecter) Find(ctx any, c any, obj any) *MockFinder_Find_Call {
	return &MockFinder_Find_Call{Call: _e.mock.On("Find", ctx, c, obj)}
}

func (_c *MockFinder_Find_Call) Run(run func(ctx context.Context, c clients.SigNoz, obj resources.Object)) *MockFinder_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clients.SigNoz
		if args[1] != nil {
			arg1 = args[1].(clients.SigNoz)
		}
		var arg2 resources.Object
		if args[2] != nil {
			arg2 = args[2].(resources.Object)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFinder_Find_Call) Return(sigNozResources []*v1alpha1.SigNozResource, err error) *MockFinder_Find_Call {
	_c.Call.Return(sigNozResources, err)
	return _c
}

func (_c *MockFinder_Find_Call) RunAndReturn(run func(ctx context.Context, c clients.SigNoz, obj resources.Object) ([]*v1alpha1.SigNozResource, error)) *MockFinder_Find_Call {
	_c.Call.Return(run)
	return _c
}
