// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcestest

import (
	"encoding/json"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/resources"
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockObject creates a new instance of MockObject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObject(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObject {
	mock := &MockObject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObject is an autogenerated mock type for the Object type
type MockObject struct {
	mock.Mock
}

type MockObject_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObject) EXPECT() *MockObject_Expecter {
	return &MockObject_Expecter{mock: &_m.Mock}
}

// Body provides a mock function for the type MockObject
func (_mock *MockObject) Body() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Body")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObject_Body_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Body'
type MockObject_Body_Call struct {
	*mock.Call
}

// Body is a helper method to define mock.On call
func (_e *MockObject_Expecter) Body() *MockObject_Body_Call {
	return &MockObject_Body_Call{Call: _e.mock.On("Body")}
}

func (_c *MockObject_Body_Call) Run(run func()) *MockObject_Body_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_Body_Call) Return(rawMessage json.RawMessage, err error) *MockObject_Body_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockObject_Body_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockObject_Body_Call {
	_c.Call.Return(run)
	return _c
}

// Compare provides a mock function for the type MockObject
func (_mock *MockObject) Compare(response json.RawMessage) (resources.CompareResult, error) {
	ret := _mock.Called(response)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 resources.CompareResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) (resources.CompareResult, error)); ok {
		return returnFunc(response)
	}
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) resources.CompareResult); ok {
		r0 = returnFunc(response)
	} else {
		r0 = ret.Get(0).(resources.CompareResult)
	}
	if returnFunc, ok := ret.Get(1).(func(json.RawMessage) error); ok {
		r1 = returnFunc(response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObject_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type MockObject_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - response json.RawMessage
func (_e *MockObject_Expecter) Compare(response any) *MockObject_Compare_Call {
	return &MockObject_Compare_Call{Call: _e.mock.On("Compare", response)}
}

func (_c *MockObject_Compare_Call) Run(run func(response json.RawMessage)) *MockObject_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 json.RawMessage
		if args[0] != nil {
			arg0 = args[0].(json.RawMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObject_Compare_Call) Return(compareResult resources.CompareResult, err error) *MockObject_Compare_Call {
	_c.Call.Return(compareResult, err)
	return _c
}

func (_c *MockObject_Compare_Call) RunAndReturn(run func(response json.RawMessage) (resources.CompareResult, error)) *MockObject_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMethodAndPath provides a mock function for the type MockObject
func (_mock *MockObject) CreateMethodAndPath() (string, string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CreateMethodAndPath")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func() (string, string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockObject_CreateMethodAndPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMethodAndPath'
type MockObject_CreateMethodAndPath_Call struct {
	*mock.Call
}

// CreateMethodAndPath is a helper method to define mock.On call
func (_e *MockObject_Expecter) CreateMethodAndPath() *MockObject_CreateMethodAndPath_Call {
	return &MockObject_CreateMethodAndPath_Call{Call: _e.mock.On("CreateMethodAndPath")}
}

func (_c *MockObject_CreateMethodAndPath_Call) Run(run func()) *MockObject_CreateMethodAndPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_CreateMethodAndPath_Call) Return(s string, s1 string) *MockObject_CreateMethodAndPath_Call {
	_c.Call.Return(s, s1)
	return _c
}

func (_c *MockObject_CreateMethodAndPath_Call) RunAndReturn(run func() (string, string)) *MockObject_CreateMethodAndPath_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMethodAndPath provides a mock function for the type MockObject
func (_mock *MockObject) DeleteMethodAndPath(sigNozResource *v1alpha1.SigNozResource) (string, string) {
	ret := _mock.Called(sigNozResource)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMethodAndPath")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.SigNozResource) (string, string)); ok {
		return returnFunc(sigNozResource)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.SigNozResource) string); ok {
		r0 = returnFunc(sigNozResource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*v1alpha1.SigNozResource) string); ok {
		r1 = returnFunc(sigNozResource)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockObject_DeleteMethodAndPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMethodAndPath'
type MockObject_DeleteMethodAndPath_Call struct {
	*mock.Call
}

// DeleteMethodAndPath is a helper method to define mock.On call
//   - sigNozResource *v1alpha1.SigNozResource
func (_e *MockObject_Expecter) DeleteMethodAndPath(sigNozResource any) *MockObject_DeleteMethodAndPath_Call {
	return &MockObject_DeleteMethodAndPath_Call{Call: _e.mock.On("DeleteMethodAndPath", sigNozResource)}
}

func (_c *MockObject_DeleteMethodAndPath_Call) Run(run func(sigNozResource *v1alpha1.SigNozResource)) *MockObject_DeleteMethodAndPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.SigNozResource
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.SigNozResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObject_DeleteMethodAndPath_Call) Return(s string, s1 string) *MockObject_DeleteMethodAndPath_Call {
	_c.Call.Return(s, s1)
	return _c
}

func (_c *MockObject_DeleteMethodAndPath_Call) RunAndReturn(run func(sigNozResource *v1alpha1.SigNozResource) (string, string)) *MockObject_DeleteMethodAndPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoreSpec provides a mock function for the type MockObject
func (_mock *MockObject) GetCoreSpec() *v1alpha1.CoreSpec {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCoreSpec")
	}

	var r0 *v1alpha1.CoreSpec
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.CoreSpec); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CoreSpec)
		}
	}
	return r0
}

// MockObject_GetCoreSpec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoreSpec'
type MockObject_GetCoreSpec_Call struct {
	*mock.Call
}

// GetCoreSpec is a helper method to define mock.On call
func (_e *MockObject_Expecter) GetCoreSpec() *MockObject_GetCoreSpec_Call {
	return &MockObject_GetCoreSpec_Call{Call: _e.mock.On("GetCoreSpec")}
}

func (_c *MockObject_GetCoreSpec_Call) Run(run func()) *MockObject_GetCoreSpec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_GetCoreSpec_Call) Return(coreSpec *v1alpha1.CoreSpec) *MockObject_GetCoreSpec_Call {
	_c.Call.Return(coreSpec)
	return _c
}

func (_c *MockObject_GetCoreSpec_Call) RunAndReturn(run func() *v1alpha1.CoreSpec) *MockObject_GetCoreSpec_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoreStatus provides a mock function for the type MockObject
func (_mock *MockObject) GetCoreStatus() *v1alpha1.CoreStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCoreStatus")
	}

	var r0 *v1alpha1.CoreStatus
	if returnFunc, ok := ret.Get(0).(func() *v1alpha1.CoreStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.CoreStatus)
		}
	}
	return r0
}

// MockObject_GetCoreStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoreStatus'
type MockObject_GetCoreStatus_Call struct {
	*mock.Call
}

// GetCoreStatus is a helper method to define mock.On call
func (_e *MockObject_Expecter) GetCoreStatus() *MockObject_GetCoreStatus_Call {
	return &MockObject_GetCoreStatus_Call{Call: _e.mock.On("GetCoreStatus")}
}

func (_c *MockObject_GetCoreStatus_Call) Run(run func()) *MockObject_GetCoreStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_GetCoreStatus_Call) Return(coreStatus *v1alpha1.CoreStatus) *MockObject_GetCoreStatus_Call {
	_c.Call.Return(coreStatus)
	return _c
}

func (_c *MockObject_GetCoreStatus_Call) RunAndReturn(run func() *v1alpha1.CoreStatus) *MockObject_GetCoreStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockObject
func (_mock *MockObject) Hash() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObject_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockObject_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
func (_e *MockObject_Expecter) Hash() *MockObject_Hash_Call {
	return &MockObject_Hash_Call{Call: _e.mock.On("Hash")}
}

func (_c *MockObject_Hash_Call) Run(run func()) *MockObject_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_Hash_Call) Return(s string, err error) *MockObject_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockObject_Hash_Call) RunAndReturn(run func() (string, error)) *MockObject_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// Identity provides a mock function for the type MockObject
func (_mock *MockObject) Identity() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Identity")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObject_Identity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Identity'
type MockObject_Identity_Call struct {
	*mock.Call
}

// Identity is a helper method to define mock.On call
func (_e *MockObject_Expecter) Identity() *MockObject_Identity_Call {
	return &MockObject_Identity_Call{Call: _e.mock.On("Identity")}
}

func (_c *MockObject_Identity_Call) Run(run func()) *MockObject_Identity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_Identity_Call) Return(s string, err error) *MockObject_Identity_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockObject_Identity_Call) RunAndReturn(run func() (string, error)) *MockObject_Identity_Call {
	_c.Call.Return(run)
	return _c
}

// ImmutableFields provides a mock function for the type MockObject
func (_mock *MockObject) ImmutableFields() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ImmutableFields")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockObject_ImmutableFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImmutableFields'
type MockObject_ImmutableFields_Call struct {
	*mock.Call
}

// ImmutableFields is a helper method to define mock.On call
func (_e *MockObject_Expecter) ImmutableFields() *MockObject_ImmutableFields_Call {
	return &MockObject_ImmutableFields_Call{Call: _e.mock.On("ImmutableFields")}
}

func (_c *MockObject_ImmutableFields_Call) Run(run func()) *MockObject_ImmutableFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_ImmutableFields_Call) Return(strings []string) *MockObject_ImmutableFields_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockObject_ImmutableFields_Call) RunAndReturn(run func() []string) *MockObject_ImmutableFields_Call {
	_c.Call.Return(run)
	return _c
}

// K8sObject provides a mock function for the type MockObject
func (_mock *MockObject) K8sObject() client.Object {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for K8sObject")
	}

	var r0 client.Object
	if returnFunc, ok := ret.Get(0).(func() client.Object); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Object)
		}
	}
	return r0
}

// MockObject_K8sObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'K8sObject'
type MockObject_K8sObject_Call struct {
	*mock.Call
}

// K8sObject is a helper method to define mock.On call
func (_e *MockObject_Expecter) K8sObject() *MockObject_K8sObject_Call {
	return &MockObject_K8sObject_Call{Call: _e.mock.On("K8sObject")}
}

func (_c *MockObject_K8sObject_Call) Run(run func()) *MockObject_K8sObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_K8sObject_Call) Return(object client.Object) *MockObject_K8sObject_Call {
	_c.Call.Return(object)
	return _c
}

func (_c *MockObject_K8sObject_Call) RunAndReturn(run func() client.Object) *MockObject_K8sObject_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMethodAndPath provides a mock function for the type MockObject
func (_mock *MockObject) ReadMethodAndPath(sigNozResource *v1alpha1.SigNozResource) (string, string) {
	ret := _mock.Called(sigNozResource)

	if len(ret) == 0 {
		panic("no return value specified for ReadMethodAndPath")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.SigNozResource) (string, string)); ok {
		return returnFunc(sigNozResource)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.SigNozResource) string); ok {
		r0 = returnFunc(sigNozResource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*v1alpha1.SigNozResource) string); ok {
		r1 = returnFunc(sigNozResource)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockObject_ReadMethodAndPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMethodAndPath'
type MockObject_ReadMethodAndPath_Call struct {
	*mock.Call
}

// ReadMethodAndPath is a helper method to define mock.On call
//   - sigNozResource *v1alpha1.SigNozResource
func (_e *MockObject_Expecter) ReadMethodAndPath(sigNozResource any) *MockObject_ReadMethodAndPath_Call {
	return &MockObject_ReadMethodAndPath_Call{Call: _e.mock.On("ReadMethodAndPath", sigNozResource)}
}

func (_c *MockObject_ReadMethodAndPath_Call) Run(run func(sigNozResource *v1alpha1.SigNozResource)) *MockObject_ReadMethodAndPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.SigNozResource
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.SigNozResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObject_ReadMethodAndPath_Call) Return(s string, s1 string) *MockObject_ReadMethodAndPath_Call {
	_c.Call.Return(s, s1)
	return _c
}

func (_c *MockObject_ReadMethodAndPath_Call) RunAndReturn(run func(sigNozResource *v1alpha1.SigNozResource) (string, string)) *MockObject_ReadMethodAndPath_Call {
	_c.Call.Return(run)
	return _c
}

// ToSigNozResource provides a mock function for the type MockObject
func (_mock *MockObject) ToSigNozResource(response json.RawMessage) (*v1alpha1.SigNozResource, error) {
	ret := _mock.Called(response)

	if len(ret) == 0 {
		panic("no return value specified for ToSigNozResource")
	}

	var r0 *v1alpha1.SigNozResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) (*v1alpha1.SigNozResource, error)); ok {
		return returnFunc(response)
	}
	if returnFunc, ok := ret.Get(0).(func(json.RawMessage) *v1alpha1.SigNozResource); ok {
		r0 = returnFunc(response)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.SigNozResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(json.RawMessage) error); ok {
		r1 = returnFunc(response)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObject_ToSigNozResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSigNozResource'
type MockObject_ToSigNozResource_Call struct {
	*mock.Call
}

// ToSigNozResource is a helper method to define mock.On call
//   - response json.RawMessage
func (_e *MockObject_Expecter) ToSigNozResource(response any) *MockObject_ToSigNozResource_Call {
	return &MockObject_ToSigNozResource_Call{Call: _e.mock.On("ToSigNozResource", response)}
}

func (_c *MockObject_ToSigNozResource_Call) Run(run func(response json.RawMessage)) *MockObject_ToSigNozResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 json.RawMessage
		if args[0] != nil {
			arg0 = args[0].(json.RawMessage)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObject_ToSigNozResource_Call) Return(sigNozResource *v1alpha1.SigNozResource, err error) *MockObject_ToSigNozResource_Call {
	_c.Call.Return(sigNozResource, err)
	return _c
}

func (_c *MockObject_ToSigNozResource_Call) RunAndReturn(run func(response json.RawMessage) (*v1alpha1.SigNozResource, error)) *MockObject_ToSigNozResource_Call {
	_c.Call.Return(run)
	return _c
}

// ToUpdate provides a mock function for the type MockObject
func (_mock *MockObject) ToUpdate() (json.RawMessage, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToUpdate")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (json.RawMessage, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() json.RawMessage); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObject_ToUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToUpdate'
type MockObject_ToUpdate_Call struct {
	*mock.Call
}

// ToUpdate is a helper method to define mock.On call
func (_e *MockObject_Expecter) ToUpdate() *MockObject_ToUpdate_Call {
	return &MockObject_ToUpdate_Call{Call: _e.mock.On("ToUpdate")}
}

func (_c *MockObject_ToUpdate_Call) Run(run func()) *MockObject_ToUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_ToUpdate_Call) Return(rawMessage json.RawMessage, err error) *MockObject_ToUpdate_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *MockObject_ToUpdate_Call) RunAndReturn(run func() (json.RawMessage, error)) *MockObject_ToUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatableFields provides a mock function for the type MockObject
func (_mock *MockObject) UpdatableFields() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UpdatableFields")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockObject_UpdatableFields_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatableFields'
type MockObject_UpdatableFields_Call struct {
	*mock.Call
}

// UpdatableFields is a helper method to define mock.On call
func (_e *MockObject_Expecter) UpdatableFields() *MockObject_UpdatableFields_Call {
	return &MockObject_UpdatableFields_Call{Call: _e.mock.On("UpdatableFields")}
}

func (_c *MockObject_UpdatableFields_Call) Run(run func()) *MockObject_UpdatableFields_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockObject_UpdatableFields_Call) Return(strings []string) *MockObject_UpdatableFields_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockObject_UpdatableFields_Call) RunAndReturn(run func() []string) *MockObject_UpdatableFields_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMethodAndPath provides a mock function for the type MockObject
func (_mock *MockObject) UpdateMethodAndPath(sigNozResource *v1alpha1.SigNozResource) (string, string) {
	ret := _mock.Called(sigNozResource)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMethodAndPath")
	}

	var r0 string
	var r1 string
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.SigNozResource) (string, string)); ok {
		return returnFunc(sigNozResource)
	}
	if returnFunc, ok := ret.Get(0).(func(*v1alpha1.SigNozResource) string); ok {
		r0 = returnFunc(sigNozResource)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*v1alpha1.SigNozResource) string); ok {
		r1 = returnFunc(sigNozResource)
	} else {
		r1 = ret.Get(1).(string)
	}
	return r0, r1
}

// MockObject_UpdateMethodAndPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMethodAndPath'
type MockObject_UpdateMethodAndPath_Call struct {
	*mock.Call
}

// UpdateMethodAndPath is a helper method to define mock.On call
//   - sigNozResource *v1alpha1.SigNozResource
func (_e *MockObject_Expecter) UpdateMethodAndPath(sigNozResource any) *MockObject_UpdateMethodAndPath_Call {
	return &MockObject_UpdateMethodAndPath_Call{Call: _e.mock.On("UpdateMethodAndPath", sigNozResource)}
}

func (_c *MockObject_UpdateMethodAndPath_Call) Run(run func(sigNozResource *v1alpha1.SigNozResource)) *MockObject_UpdateMethodAndPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *v1alpha1.SigNozResource
		if args[0] != nil {
			arg0 = args[0].(*v1alpha1.SigNozResource)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockObject_UpdateMethodAndPath_Call) Return(s string, s1 string) *MockObject_UpdateMethodAndPath_Call {
	_c.Call.Return(s, s1)
	return _c
}

func (_c *MockObject_UpdateMethodAndPath_Call) RunAndReturn(run func(sigNozResource *v1alpha1.SigNozResource) (string, string)) *MockObject_UpdateMethodAndPath_Call {
	_c.Call.Return(run)
	return _c
}
