// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package resourcestest

import (
	"context"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/clients"
	"github.com/SigNoz/signoz-operator/internal/resources"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdapter creates a new instance of MockAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdapter {
	mock := &MockAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdapter is an autogenerated mock type for the Adapter type
type MockAdapter struct {
	mock.Mock
}

type MockAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdapter) EXPECT() *MockAdapter_Expecter {
	return &MockAdapter_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Create(ctx context.Context, c clients.SigNoz, obj resources.Object) (*v1alpha1.SigNozResource, error) {
	ret := _mock.Called(ctx, c, obj)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1alpha1.SigNozResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object) (*v1alpha1.SigNozResource, error)); ok {
		return returnFunc(ctx, c, obj)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object) *v1alpha1.SigNozResource); ok {
		r0 = returnFunc(ctx, c, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.SigNozResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clients.SigNoz, resources.Object) error); ok {
		r1 = returnFunc(ctx, c, obj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAdapter_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - c clients.SigNoz
//   - obj resources.Object
func (_e *MockAdapter_Expecter) Create(ctx any, c any, obj any) *MockAdapter_Create_Call {
	return &MockAdapter_Create_Call{Call: _e.mock.On("Create", ctx, c, obj)}
}

func (_c *MockAdapter_Create_Call) Run(run func(ctx context.Context, c clients.SigNoz, obj resources.Object)) *MockAdapter_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clients.SigNoz
		if args[1] != nil {
			arg1 = args[1].(clients.SigNoz)
		}
		var arg2 resources.Object
		if args[2] != nil {
			arg2 = args[2].(resources.Object)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_Create_Call) Return(sigNozResource *v1alpha1.SigNozResource, err error) *MockAdapter_Create_Call {
	_c.Call.Return(sigNozResource, err)
	return _c
}

func (_c *MockAdapter_Create_Call) RunAndReturn(run func(ctx context.Context, c clients.SigNoz, obj resources.Object) (*v1alpha1.SigNozResource, error)) *MockAdapter_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Delete(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource) error {
	ret := _mock.Called(ctx, c, obj, resourceMetadata)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object, *v1alpha1.SigNozResource) error); ok {
		r0 = returnFunc(ctx, c, obj, resourceMetadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAdapter_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - c clients.SigNoz
//   - obj resources.Object
//   - resourceMetadata *v1alpha1.SigNozResource
func (_e *MockAdapter_Expecter) Delete(ctx any, c any, obj any, resourceMetadata any) *MockAdapter_Delete_Call {
	return &MockAdapter_Delete_Call{Call: _e.mock.On("Delete", ctx, c, obj, resourceMetadata)}
}

func (_c *MockAdapter_Delete_Call) Run(run func(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource)) *MockAdapter_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clients.SigNoz
		if args[1] != nil {
			arg1 = args[1].(clients.SigNoz)
		}
		var arg2 resources.Object
		if args[2] != nil {
			arg2 = args[2].(resources.Object)
		}
		var arg3 *v1alpha1.SigNozResource
		if args[3] != nil {
			arg3 = args[3].(*v1alpha1.SigNozResource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapter_Delete_Call) Return(err error) *MockAdapter_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_Delete_Call) RunAndReturn(run func(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource) error) *MockAdapter_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Find(ctx context.Context, c clients.SigNoz, obj resources.Object) ([]*v1alpha1.SigNozResource, error) {
	ret := _mock.Called(ctx, c, obj)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 []*v1alpha1.SigNozResource
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object) ([]*v1alpha1.SigNozResource, error)); ok {
		return returnFunc(ctx, c, obj)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object) []*v1alpha1.SigNozResource); ok {
		r0 = returnFunc(ctx, c, obj)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*v1alpha1.SigNozResource)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clients.SigNoz, resources.Object) error); ok {
		r1 = returnFunc(ctx, c, obj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockAdapter_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - c clients.SigNoz
//   - obj resources.Object
func (_e *MockAdapter_Expecter) Find(ctx any, c any, obj any) *MockAdapter_Find_Call {
	return &MockAdapter_Find_Call{Call: _e.mock.On("Find", ctx, c, obj)}
}

func (_c *MockAdapter_Find_Call) Run(run func(ctx context.Context, c clients.SigNoz, obj resources.Object)) *MockAdapter_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clients.SigNoz
		if args[1] != nil {
			arg1 = args[1].(clients.SigNoz)
		}
		var arg2 resources.Object
		if args[2] != nil {
			arg2 = args[2].(resources.Object)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAdapter_Find_Call) Return(sigNozResources []*v1alpha1.SigNozResource, err error) *MockAdapter_Find_Call {
	_c.Call.Return(sigNozResources, err)
	return _c
}

func (_c *MockAdapter_Find_Call) RunAndReturn(run func(ctx context.Context, c clients.SigNoz, obj resources.Object) ([]*v1alpha1.SigNozResource, error)) *MockAdapter_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Read(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource) (map[string]any, error) {
	ret := _mock.Called(ctx, c, obj, resourceMetadata)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object, *v1alpha1.SigNozResource) (map[string]any, error)); ok {
		return returnFunc(ctx, c, obj, resourceMetadata)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object, *v1alpha1.SigNozResource) map[string]any); ok {
		r0 = returnFunc(ctx, c, obj, resourceMetadata)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, clients.SigNoz, resources.Object, *v1alpha1.SigNozResource) error); ok {
		r1 = returnFunc(ctx, c, obj, resourceMetadata)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdapter_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockAdapter_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - c clients.SigNoz
//   - obj resources.Object
//   - resourceMetadata *v1alpha1.SigNozResource
func (_e *MockAdapter_Expecter) Read(ctx any, c any, obj any, resourceMetadata any) *MockAdapter_Read_Call {
	return &MockAdapter_Read_Call{Call: _e.mock.On("Read", ctx, c, obj, resourceMetadata)}
}

func (_c *MockAdapter_Read_Call) Run(run func(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource)) *MockAdapter_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clients.SigNoz
		if args[1] != nil {
			arg1 = args[1].(clients.SigNoz)
		}
		var arg2 resources.Object
		if args[2] != nil {
			arg2 = args[2].(resources.Object)
		}
		var arg3 *v1alpha1.SigNozResource
		if args[3] != nil {
			arg3 = args[3].(*v1alpha1.SigNozResource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapter_Read_Call) Return(stringToAnyMoqParam map[string]any, err error) *MockAdapter_Read_Call {
	_c.Call.Return(stringToAnyMoqParam, err)
	return _c
}

func (_c *MockAdapter_Read_Call) RunAndReturn(run func(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource) (map[string]any, error)) *MockAdapter_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockAdapter
func (_mock *MockAdapter) Update(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource) error {
	ret := _mock.Called(ctx, c, obj, resourceMetadata)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, clients.SigNoz, resources.Object, *v1alpha1.SigNozResource) error); ok {
		r0 = returnFunc(ctx, c, obj, resourceMetadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdapter_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAdapter_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - c clients.SigNoz
//   - obj resources.Object
//   - resourceMetadata *v1alpha1.SigNozResource
func (_e *MockAdapter_Expecter) Update(ctx any, c any, obj any, resourceMetadata any) *MockAdapter_Update_Call {
	return &MockAdapter_Update_Call{Call: _e.mock.On("Update", ctx, c, obj, resourceMetadata)}
}

func (_c *MockAdapter_Update_Call) Run(run func(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource)) *MockAdapter_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 clients.SigNoz
		if args[1] != nil {
			arg1 = args[1].(clients.SigNoz)
		}
		var arg2 resources.Object
		if args[2] != nil {
			arg2 = args[2].(resources.Object)
		}
		var arg3 *v1alpha1.SigNozResource
		if args[3] != nil {
			arg3 = args[3].(*v1alpha1.SigNozResource)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAdapter_Update_Call) Return(err error) *MockAdapter_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdapter_Update_Call) RunAndReturn(run func(ctx context.Context, c clients.SigNoz, obj resources.Object, resourceMetadata *v1alpha1.SigNozResource) error) *MockAdapter_Update_Call {
	_c.Call.Return(run)
	return _c
}
