# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/resources.signoz.io_providerconfigs.yaml
- bases/resources.signoz.io_clusterproviderconfigs.yaml
- bases/resources.signoz.io_users.yaml
- bases/resources.signoz.io_authdomains.yaml
- bases/resources.signoz.io_dashboards.yaml
- bases/resources.signoz.io_savedviews.yaml
- bases/resources.signoz.io_plannedmaintenances.yaml
- bases/resources.signoz.io_roles.yaml
- bases/resources.signoz.io_routepolicies.yaml
- bases/resources.signoz.io_rules.yaml
- bases/resources.signoz.io_serviceaccounts.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
