apiVersion: apps/v1
kind: Deployment
metadata:
  name: signoz-operator
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: signoz-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: signoz-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: signoz-operator
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: signoz-operator
      containers:
      - name: controller
        image: controller:latest
        command:
        - /manager
        ports:
        - name: health
          protocol: TCP
          containerPort: 8081
        env:
        - name: SIGNOZ_OPERATOR_OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SIGNOZ_OPERATOR_LEADER_ELECT
          value: "true"
        - name: SIGNOZ_OPERATOR_HEALTH_PROBE_BIND_ADDRESS
          value: ":8081"
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        livenessProbe:
          httpGet:
            port: 8081
            path: /healthz
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            port: 8081
            path: /readyz
          initialDelaySeconds: 5
          periodSeconds: 10
        imagePullPolicy: IfNotPresent
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
