// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package providerconfigtest

import (
	"context"

	"github.com/SigNoz/signoz-operator/api/resources/v1alpha1"
	"github.com/SigNoz/signoz-operator/internal/providerconfig"
	mock "github.com/stretchr/testify/mock"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockResolver creates a new instance of MockResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResolver {
	mock := &MockResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResolver is an autogenerated mock type for the Resolver type
type MockResolver struct {
	mock.Mock
}

type MockResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResolver) EXPECT() *MockResolver_Expecter {
	return &MockResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function for the type MockResolver
func (_mock *MockResolver) Resolve(ctx context.Context, namespace string, spec *v1alpha1.ProviderConfigSpec) (*providerconfig.ResolvedProviderConfigSpec, map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string, error) {
	ret := _mock.Called(ctx, namespace, spec)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 *providerconfig.ResolvedProviderConfigSpec
	var r1 map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProviderConfigSpec) (*providerconfig.ResolvedProviderConfigSpec, map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string, error)); ok {
		return returnFunc(ctx, namespace, spec)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ProviderConfigSpec) *providerconfig.ResolvedProviderConfigSpec); ok {
		r0 = returnFunc(ctx, namespace, spec)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providerconfig.ResolvedProviderConfigSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ProviderConfigSpec) map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string); ok {
		r1 = returnFunc(ctx, namespace, spec)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, *v1alpha1.ProviderConfigSpec) error); ok {
		r2 = returnFunc(ctx, namespace, spec)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - spec *v1alpha1.ProviderConfigSpec
func (_e *MockResolver_Expecter) Resolve(ctx any, namespace any, spec any) *MockResolver_Resolve_Call {
	return &MockResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, namespace, spec)}
}

func (_c *MockResolver_Resolve_Call) Run(run func(ctx context.Context, namespace string, spec *v1alpha1.ProviderConfigSpec)) *MockResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *v1alpha1.ProviderConfigSpec
		if args[2] != nil {
			arg2 = args[2].(*v1alpha1.ProviderConfigSpec)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResolver_Resolve_Call) Return(resolvedProviderConfigSpec *providerconfig.ResolvedProviderConfigSpec, providerConfigObservedRefKindToObjectKeyToString map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string, err error) *MockResolver_Resolve_Call {
	_c.Call.Return(resolvedProviderConfigSpec, providerConfigObservedRefKindToObjectKeyToString, err)
	return _c
}

func (_c *MockResolver_Resolve_Call) RunAndReturn(run func(ctx context.Context, namespace string, spec *v1alpha1.ProviderConfigSpec) (*providerconfig.ResolvedProviderConfigSpec, map[v1alpha1.ProviderConfigObservedRefKind]map[client.ObjectKey]string, error)) *MockResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveRef provides a mock function for the type MockResolver
func (_mock *MockResolver) ResolveRef(ctx context.Context, ref v1alpha1.ProviderConfigRef, resourceNamespace string, operatorNamespace string) (*providerconfig.ResolvedProviderConfigSpec, error) {
	ret := _mock.Called(ctx, ref, resourceNamespace, operatorNamespace)

	if len(ret) == 0 {
		panic("no return value specified for ResolveRef")
	}

	var r0 *providerconfig.ResolvedProviderConfigSpec
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1alpha1.ProviderConfigRef, string, string) (*providerconfig.ResolvedProviderConfigSpec, error)); ok {
		return returnFunc(ctx, ref, resourceNamespace, operatorNamespace)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, v1alpha1.ProviderConfigRef, string, string) *providerconfig.ResolvedProviderConfigSpec); ok {
		r0 = returnFunc(ctx, ref, resourceNamespace, operatorNamespace)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*providerconfig.ResolvedProviderConfigSpec)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, v1alpha1.ProviderConfigRef, string, string) error); ok {
		r1 = returnFunc(ctx, ref, resourceNamespace, operatorNamespace)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResolver_ResolveRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveRef'
type MockResolver_ResolveRef_Call struct {
	*mock.Call
}

// ResolveRef is a helper method to define mock.On call
//   - ctx context.Context
//   - ref v1alpha1.ProviderConfigRef
//   - resourceNamespace string
//   - operatorNamespace string
func (_e *MockResolver_Expecter) ResolveRef(ctx any, ref any, resourceNamespace any, operatorNamespace any) *MockResolver_ResolveRef_Call {
	return &MockResolver_ResolveRef_Call{Call: _e.mock.On("ResolveRef", ctx, ref, resourceNamespace, operatorNamespace)}
}

func (_c *MockResolver_ResolveRef_Call) Run(run func(ctx context.Context, ref v1alpha1.ProviderConfigRef, resourceNamespace string, operatorNamespace string)) *MockResolver_ResolveRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 v1alpha1.ProviderConfigRef
		if args[1] != nil {
			arg1 = args[1].(v1alpha1.ProviderConfigRef)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResolver_ResolveRef_Call) Return(resolvedProviderConfigSpec *providerconfig.ResolvedProviderConfigSpec, err error) *MockResolver_ResolveRef_Call {
	_c.Call.Return(resolvedProviderConfigSpec, err)
	return _c
}

func (_c *MockResolver_ResolveRef_Call) RunAndReturn(run func(ctx context.Context, ref v1alpha1.ProviderConfigRef, resourceNamespace string, operatorNamespace string) (*providerconfig.ResolvedProviderConfigSpec, error)) *MockResolver_ResolveRef_Call {
	_c.Call.Return(run)
	return _c
}
