// Code generated by skaff operator types DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type PlannedMaintenanceObjectSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +kubebuilder:validation:Required
	Schedule PlannedMaintenanceSchedule `json:"schedule"`

	// +optional
	AlertIds []string `json:"alertIds,omitempty"`

	// +optional
	Description string `json:"description,omitempty"`

	// +optional
	Scope string `json:"scope,omitempty"`
}

type PlannedMaintenanceSchedule struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	StartTime string `json:"startTime"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Timezone string `json:"timezone"`

	// +optional
	EndTime string `json:"endTime,omitempty"`

	// +optional
	Recurrence *PlannedMaintenanceRecurrence `json:"recurrence,omitempty"`
}

type PlannedMaintenanceRecurrence struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Duration string `json:"duration"`

	// +kubebuilder:validation:Enum=daily;weekly;monthly
	// +kubebuilder:validation:Required
	RepeatType string `json:"repeatType"`

	// +optional
	RepeatOn []string `json:"repeatOn,omitempty"`
}

// +kubebuilder:validation:MinProperties=1
// +kubebuilder:validation:MaxProperties=1
type PlannedMaintenanceObjectTemplate struct {
	// +optional
	Spec *PlannedMaintenanceObjectSpec `json:"spec,omitempty"`

	// +optional
	// +kubebuilder:validation:MinLength=1
	JSONSpec *string `json:"jsonSpec,omitempty"`
}

type PlannedMaintenanceSpec struct {
	CoreSpec `json:",inline"`

	// +kubebuilder:validation:Required
	ObjectTemplate PlannedMaintenanceObjectTemplate `json:"objectTemplate"`
}

type PlannedMaintenanceStatus struct {
	CoreStatus `json:",inline"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="ID",type=string,JSONPath=".status.signozResource.id"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

type PlannedMaintenance struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec PlannedMaintenanceSpec `json:"spec"`

	// +optional
	Status PlannedMaintenanceStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type PlannedMaintenanceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []PlannedMaintenance `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &PlannedMaintenance{}, &PlannedMaintenanceList{})
		return nil
	})
}
