// Code generated by skaff operator types DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type ServiceAccountObjectSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`
}

// +kubebuilder:validation:MinProperties=1
// +kubebuilder:validation:MaxProperties=1
type ServiceAccountObjectTemplate struct {
	// +optional
	Spec *ServiceAccountObjectSpec `json:"spec,omitempty"`

	// +optional
	// +kubebuilder:validation:MinLength=1
	JSONSpec *string `json:"jsonSpec,omitempty"`
}

type ServiceAccountSpec struct {
	CoreSpec `json:",inline"`

	// +kubebuilder:validation:Required
	ObjectTemplate ServiceAccountObjectTemplate `json:"objectTemplate"`
}

type ServiceAccountStatus struct {
	CoreStatus `json:",inline"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="ID",type=string,JSONPath=".status.signozResource.id"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

type ServiceAccount struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec ServiceAccountSpec `json:"spec"`

	// +optional
	Status ServiceAccountStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type ServiceAccountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []ServiceAccount `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &ServiceAccount{}, &ServiceAccountList{})
		return nil
	})
}
