//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomain) DeepCopyInto(out *AuthDomain) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomain.
func (in *AuthDomain) DeepCopy() *AuthDomain {
	if in == nil {
		return nil
	}
	out := new(AuthDomain)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthDomain) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainAttributeMapping) DeepCopyInto(out *AuthDomainAttributeMapping) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainAttributeMapping.
func (in *AuthDomainAttributeMapping) DeepCopy() *AuthDomainAttributeMapping {
	if in == nil {
		return nil
	}
	out := new(AuthDomainAttributeMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainConfig) DeepCopyInto(out *AuthDomainConfig) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainConfig.
func (in *AuthDomainConfig) DeepCopy() *AuthDomainConfig {
	if in == nil {
		return nil
	}
	out := new(AuthDomainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainConfigSpec) DeepCopyInto(out *AuthDomainConfigSpec) {
	*out = *in
	if in.AllowedGroups != nil {
		in, out := &in.AllowedGroups, &out.AllowedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AttributeMapping != nil {
		in, out := &in.AttributeMapping, &out.AttributeMapping
		*out = new(AuthDomainAttributeMapping)
		**out = **in
	}
	if in.ClaimMapping != nil {
		in, out := &in.ClaimMapping, &out.ClaimMapping
		*out = new(AuthDomainAttributeMapping)
		**out = **in
	}
	if in.DomainToAdminEmail != nil {
		in, out := &in.DomainToAdminEmail, &out.DomainToAdminEmail
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainConfigSpec.
func (in *AuthDomainConfigSpec) DeepCopy() *AuthDomainConfigSpec {
	if in == nil {
		return nil
	}
	out := new(AuthDomainConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainList) DeepCopyInto(out *AuthDomainList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthDomain, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainList.
func (in *AuthDomainList) DeepCopy() *AuthDomainList {
	if in == nil {
		return nil
	}
	out := new(AuthDomainList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthDomainList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainObjectSpec) DeepCopyInto(out *AuthDomainObjectSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	if in.RoleMapping != nil {
		in, out := &in.RoleMapping, &out.RoleMapping
		*out = new(AuthDomainRoleMapping)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainObjectSpec.
func (in *AuthDomainObjectSpec) DeepCopy() *AuthDomainObjectSpec {
	if in == nil {
		return nil
	}
	out := new(AuthDomainObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainObjectTemplate) DeepCopyInto(out *AuthDomainObjectTemplate) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(AuthDomainObjectSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JSONSpec != nil {
		in, out := &in.JSONSpec, &out.JSONSpec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainObjectTemplate.
func (in *AuthDomainObjectTemplate) DeepCopy() *AuthDomainObjectTemplate {
	if in == nil {
		return nil
	}
	out := new(AuthDomainObjectTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainRoleMapping) DeepCopyInto(out *AuthDomainRoleMapping) {
	*out = *in
	if in.GroupMappings != nil {
		in, out := &in.GroupMappings, &out.GroupMappings
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainRoleMapping.
func (in *AuthDomainRoleMapping) DeepCopy() *AuthDomainRoleMapping {
	if in == nil {
		return nil
	}
	out := new(AuthDomainRoleMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainSpec) DeepCopyInto(out *AuthDomainSpec) {
	*out = *in
	in.CoreSpec.DeepCopyInto(&out.CoreSpec)
	in.ObjectTemplate.DeepCopyInto(&out.ObjectTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainSpec.
func (in *AuthDomainSpec) DeepCopy() *AuthDomainSpec {
	if in == nil {
		return nil
	}
	out := new(AuthDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthDomainStatus) DeepCopyInto(out *AuthDomainStatus) {
	*out = *in
	in.CoreStatus.DeepCopyInto(&out.CoreStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthDomainStatus.
func (in *AuthDomainStatus) DeepCopy() *AuthDomainStatus {
	if in == nil {
		return nil
	}
	out := new(AuthDomainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Authentication) DeepCopyInto(out *Authentication) {
	*out = *in
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(HeaderAuth)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Authentication.
func (in *Authentication) DeepCopy() *Authentication {
	if in == nil {
		return nil
	}
	out := new(Authentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfig) DeepCopyInto(out *ClusterProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfig.
func (in *ClusterProviderConfig) DeepCopy() *ClusterProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterProviderConfigList) DeepCopyInto(out *ClusterProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterProviderConfigList.
func (in *ClusterProviderConfigList) DeepCopy() *ClusterProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ClusterProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreSpec) DeepCopyInto(out *CoreSpec) {
	*out = *in
	out.ProviderConfigRef = in.ProviderConfigRef
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RetryInterval != nil {
		in, out := &in.RetryInterval, &out.RetryInterval
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreSpec.
func (in *CoreSpec) DeepCopy() *CoreSpec {
	if in == nil {
		return nil
	}
	out := new(CoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreStatus) DeepCopyInto(out *CoreStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SigNozResource != nil {
		in, out := &in.SigNozResource, &out.SigNozResource
		*out = new(SigNozResource)
		(*in).DeepCopyInto(*out)
	}
	in.ReconciledAt.DeepCopyInto(&out.ReconciledAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreStatus.
func (in *CoreStatus) DeepCopy() *CoreStatus {
	if in == nil {
		return nil
	}
	out := new(CoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Dashboard) DeepCopyInto(out *Dashboard) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Dashboard.
func (in *Dashboard) DeepCopy() *Dashboard {
	if in == nil {
		return nil
	}
	out := new(Dashboard)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Dashboard) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAggregation) DeepCopyInto(out *DashboardAggregation) {
	*out = *in
	if in.ComparisonSpaceAggregationParam != nil {
		in, out := &in.ComparisonSpaceAggregationParam, &out.ComparisonSpaceAggregationParam
		*out = new(DashboardComparisonSpaceAggregationParam)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAggregation.
func (in *DashboardAggregation) DeepCopy() *DashboardAggregation {
	if in == nil {
		return nil
	}
	out := new(DashboardAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardArg) DeepCopyInto(out *DashboardArg) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardArg.
func (in *DashboardArg) DeepCopy() *DashboardArg {
	if in == nil {
		return nil
	}
	out := new(DashboardArg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardAxes) DeepCopyInto(out *DashboardAxes) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardAxes.
func (in *DashboardAxes) DeepCopy() *DashboardAxes {
	if in == nil {
		return nil
	}
	out := new(DashboardAxes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardChartAppearance) DeepCopyInto(out *DashboardChartAppearance) {
	*out = *in
	if in.SpanGaps != nil {
		in, out := &in.SpanGaps, &out.SpanGaps
		*out = new(DashboardSpanGaps)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardChartAppearance.
func (in *DashboardChartAppearance) DeepCopy() *DashboardChartAppearance {
	if in == nil {
		return nil
	}
	out := new(DashboardChartAppearance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardCollapse) DeepCopyInto(out *DashboardCollapse) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardCollapse.
func (in *DashboardCollapse) DeepCopy() *DashboardCollapse {
	if in == nil {
		return nil
	}
	out := new(DashboardCollapse)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardComparisonSpaceAggregationParam) DeepCopyInto(out *DashboardComparisonSpaceAggregationParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardComparisonSpaceAggregationParam.
func (in *DashboardComparisonSpaceAggregationParam) DeepCopy() *DashboardComparisonSpaceAggregationParam {
	if in == nil {
		return nil
	}
	out := new(DashboardComparisonSpaceAggregationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardContent) DeepCopyInto(out *DashboardContent) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardContent.
func (in *DashboardContent) DeepCopy() *DashboardContent {
	if in == nil {
		return nil
	}
	out := new(DashboardContent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardDisplay) DeepCopyInto(out *DashboardDisplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardDisplay.
func (in *DashboardDisplay) DeepCopy() *DashboardDisplay {
	if in == nil {
		return nil
	}
	out := new(DashboardDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardFilter) DeepCopyInto(out *DashboardFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardFilter.
func (in *DashboardFilter) DeepCopy() *DashboardFilter {
	if in == nil {
		return nil
	}
	out := new(DashboardFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardFormatting) DeepCopyInto(out *DashboardFormatting) {
	*out = *in
	if in.ColumnUnits != nil {
		in, out := &in.ColumnUnits, &out.ColumnUnits
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardFormatting.
func (in *DashboardFormatting) DeepCopy() *DashboardFormatting {
	if in == nil {
		return nil
	}
	out := new(DashboardFormatting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardFunction) DeepCopyInto(out *DashboardFunction) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]DashboardArg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardFunction.
func (in *DashboardFunction) DeepCopy() *DashboardFunction {
	if in == nil {
		return nil
	}
	out := new(DashboardFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardGroupBy) DeepCopyInto(out *DashboardGroupBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardGroupBy.
func (in *DashboardGroupBy) DeepCopy() *DashboardGroupBy {
	if in == nil {
		return nil
	}
	out := new(DashboardGroupBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardHaving) DeepCopyInto(out *DashboardHaving) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardHaving.
func (in *DashboardHaving) DeepCopy() *DashboardHaving {
	if in == nil {
		return nil
	}
	out := new(DashboardHaving)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardHistogramBuckets) DeepCopyInto(out *DashboardHistogramBuckets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardHistogramBuckets.
func (in *DashboardHistogramBuckets) DeepCopy() *DashboardHistogramBuckets {
	if in == nil {
		return nil
	}
	out := new(DashboardHistogramBuckets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardItem) DeepCopyInto(out *DashboardItem) {
	*out = *in
	if in.Content != nil {
		in, out := &in.Content, &out.Content
		*out = new(DashboardContent)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardItem.
func (in *DashboardItem) DeepCopy() *DashboardItem {
	if in == nil {
		return nil
	}
	out := new(DashboardItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardKey) DeepCopyInto(out *DashboardKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardKey.
func (in *DashboardKey) DeepCopy() *DashboardKey {
	if in == nil {
		return nil
	}
	out := new(DashboardKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLayout) DeepCopyInto(out *DashboardLayout) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLayout.
func (in *DashboardLayout) DeepCopy() *DashboardLayout {
	if in == nil {
		return nil
	}
	out := new(DashboardLayout)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLayoutSpec) DeepCopyInto(out *DashboardLayoutSpec) {
	*out = *in
	if in.Display != nil {
		in, out := &in.Display, &out.Display
		*out = new(DashboardLayoutSpecDisplay)
		(*in).DeepCopyInto(*out)
	}
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DashboardItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLayoutSpec.
func (in *DashboardLayoutSpec) DeepCopy() *DashboardLayoutSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardLayoutSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLayoutSpecDisplay) DeepCopyInto(out *DashboardLayoutSpecDisplay) {
	*out = *in
	if in.Collapse != nil {
		in, out := &in.Collapse, &out.Collapse
		*out = new(DashboardCollapse)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLayoutSpecDisplay.
func (in *DashboardLayoutSpecDisplay) DeepCopy() *DashboardLayoutSpecDisplay {
	if in == nil {
		return nil
	}
	out := new(DashboardLayoutSpecDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLegend) DeepCopyInto(out *DashboardLegend) {
	*out = *in
	if in.CustomColors != nil {
		in, out := &in.CustomColors, &out.CustomColors
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLegend.
func (in *DashboardLegend) DeepCopy() *DashboardLegend {
	if in == nil {
		return nil
	}
	out := new(DashboardLegend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLimitBy) DeepCopyInto(out *DashboardLimitBy) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLimitBy.
func (in *DashboardLimitBy) DeepCopy() *DashboardLimitBy {
	if in == nil {
		return nil
	}
	out := new(DashboardLimitBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardLink) DeepCopyInto(out *DashboardLink) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardLink.
func (in *DashboardLink) DeepCopy() *DashboardLink {
	if in == nil {
		return nil
	}
	out := new(DashboardLink)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardList) DeepCopyInto(out *DashboardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Dashboard, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardList.
func (in *DashboardList) DeepCopy() *DashboardList {
	if in == nil {
		return nil
	}
	out := new(DashboardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DashboardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardObjectSpec) DeepCopyInto(out *DashboardObjectSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]DashboardTag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardObjectSpec.
func (in *DashboardObjectSpec) DeepCopy() *DashboardObjectSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardObjectTemplate) DeepCopyInto(out *DashboardObjectTemplate) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DashboardObjectSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JSONSpec != nil {
		in, out := &in.JSONSpec, &out.JSONSpec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardObjectTemplate.
func (in *DashboardObjectTemplate) DeepCopy() *DashboardObjectTemplate {
	if in == nil {
		return nil
	}
	out := new(DashboardObjectTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardOrder) DeepCopyInto(out *DashboardOrder) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(DashboardKey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardOrder.
func (in *DashboardOrder) DeepCopy() *DashboardOrder {
	if in == nil {
		return nil
	}
	out := new(DashboardOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPanel) DeepCopyInto(out *DashboardPanel) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPanel.
func (in *DashboardPanel) DeepCopy() *DashboardPanel {
	if in == nil {
		return nil
	}
	out := new(DashboardPanel)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPanelSpec) DeepCopyInto(out *DashboardPanelSpec) {
	*out = *in
	out.Display = in.Display
	in.Plugin.DeepCopyInto(&out.Plugin)
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]DashboardQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]DashboardLink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPanelSpec.
func (in *DashboardPanelSpec) DeepCopy() *DashboardPanelSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardPanelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPlugin) DeepCopyInto(out *DashboardPlugin) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPlugin.
func (in *DashboardPlugin) DeepCopy() *DashboardPlugin {
	if in == nil {
		return nil
	}
	out := new(DashboardPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardPluginSpec) DeepCopyInto(out *DashboardPluginSpec) {
	*out = *in
	if in.Axes != nil {
		in, out := &in.Axes, &out.Axes
		*out = new(DashboardAxes)
		**out = **in
	}
	if in.ChartAppearance != nil {
		in, out := &in.ChartAppearance, &out.ChartAppearance
		*out = new(DashboardChartAppearance)
		(*in).DeepCopyInto(*out)
	}
	if in.Formatting != nil {
		in, out := &in.Formatting, &out.Formatting
		*out = new(DashboardFormatting)
		(*in).DeepCopyInto(*out)
	}
	if in.HistogramBuckets != nil {
		in, out := &in.HistogramBuckets, &out.HistogramBuckets
		*out = new(DashboardHistogramBuckets)
		**out = **in
	}
	if in.Legend != nil {
		in, out := &in.Legend, &out.Legend
		*out = new(DashboardLegend)
		(*in).DeepCopyInto(*out)
	}
	if in.SelectFields != nil {
		in, out := &in.SelectFields, &out.SelectFields
		*out = make([]DashboardSelectField, len(*in))
		copy(*out, *in)
	}
	if in.Thresholds != nil {
		in, out := &in.Thresholds, &out.Thresholds
		*out = make([]DashboardThreshold, len(*in))
		copy(*out, *in)
	}
	if in.Visualization != nil {
		in, out := &in.Visualization, &out.Visualization
		*out = new(DashboardVisualization)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardPluginSpec.
func (in *DashboardPluginSpec) DeepCopy() *DashboardPluginSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuery) DeepCopyInto(out *DashboardQuery) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuery.
func (in *DashboardQuery) DeepCopy() *DashboardQuery {
	if in == nil {
		return nil
	}
	out := new(DashboardQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpec) DeepCopyInto(out *DashboardQuerySpec) {
	*out = *in
	in.Plugin.DeepCopyInto(&out.Plugin)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpec.
func (in *DashboardQuerySpec) DeepCopy() *DashboardQuerySpec {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPlugin) DeepCopyInto(out *DashboardQuerySpecPlugin) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPlugin.
func (in *DashboardQuerySpecPlugin) DeepCopy() *DashboardQuerySpecPlugin {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpec) DeepCopyInto(out *DashboardQuerySpecPluginSpec) {
	*out = *in
	if in.Aggregations != nil {
		in, out := &in.Aggregations, &out.Aggregations
		*out = make([]DashboardAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(DashboardFilter)
		**out = **in
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]DashboardFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]DashboardGroupBy, len(*in))
		copy(*out, *in)
	}
	if in.Having != nil {
		in, out := &in.Having, &out.Having
		*out = new(DashboardHaving)
		**out = **in
	}
	if in.LimitBy != nil {
		in, out := &in.LimitBy, &out.LimitBy
		*out = new(DashboardLimitBy)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]DashboardOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]DashboardQuerySpecPluginSpecQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecondaryAggregations != nil {
		in, out := &in.SecondaryAggregations, &out.SecondaryAggregations
		*out = make([]DashboardSecondaryAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectFields != nil {
		in, out := &in.SelectFields, &out.SelectFields
		*out = make([]DashboardSelectField, len(*in))
		copy(*out, *in)
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.StepInterval != nil {
		in, out := &in.StepInterval, &out.StepInterval
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpec.
func (in *DashboardQuerySpecPluginSpec) DeepCopy() *DashboardQuerySpecPluginSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpecQuery) DeepCopyInto(out *DashboardQuerySpecPluginSpecQuery) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(DashboardQuerySpecPluginSpecQuerySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpecQuery.
func (in *DashboardQuerySpecPluginSpecQuery) DeepCopy() *DashboardQuerySpecPluginSpecQuery {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpecQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpecQuerySpec) DeepCopyInto(out *DashboardQuerySpecPluginSpecQuerySpec) {
	*out = *in
	if in.Aggregations != nil {
		in, out := &in.Aggregations, &out.Aggregations
		*out = make([]DashboardQuerySpecPluginSpecQuerySpecAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(DashboardQuerySpecPluginSpecQuerySpecFilter)
		**out = **in
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]DashboardFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]DashboardGroupBy, len(*in))
		copy(*out, *in)
	}
	if in.Having != nil {
		in, out := &in.Having, &out.Having
		*out = new(DashboardQuerySpecPluginSpecQuerySpecHaving)
		**out = **in
	}
	if in.LimitBy != nil {
		in, out := &in.LimitBy, &out.LimitBy
		*out = new(DashboardQuerySpecPluginSpecQuerySpecLimitBy)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]DashboardOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecondaryAggregations != nil {
		in, out := &in.SecondaryAggregations, &out.SecondaryAggregations
		*out = make([]DashboardSecondaryAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectFields != nil {
		in, out := &in.SelectFields, &out.SelectFields
		*out = make([]DashboardSelectField, len(*in))
		copy(*out, *in)
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.StepInterval != nil {
		in, out := &in.StepInterval, &out.StepInterval
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpecQuerySpec.
func (in *DashboardQuerySpecPluginSpecQuerySpec) DeepCopy() *DashboardQuerySpecPluginSpecQuerySpec {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpecQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpecQuerySpecAggregation) DeepCopyInto(out *DashboardQuerySpecPluginSpecQuerySpecAggregation) {
	*out = *in
	if in.ComparisonSpaceAggregationParam != nil {
		in, out := &in.ComparisonSpaceAggregationParam, &out.ComparisonSpaceAggregationParam
		*out = new(DashboardComparisonSpaceAggregationParam)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpecQuerySpecAggregation.
func (in *DashboardQuerySpecPluginSpecQuerySpecAggregation) DeepCopy() *DashboardQuerySpecPluginSpecQuerySpecAggregation {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpecQuerySpecAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpecQuerySpecFilter) DeepCopyInto(out *DashboardQuerySpecPluginSpecQuerySpecFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpecQuerySpecFilter.
func (in *DashboardQuerySpecPluginSpecQuerySpecFilter) DeepCopy() *DashboardQuerySpecPluginSpecQuerySpecFilter {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpecQuerySpecFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpecQuerySpecHaving) DeepCopyInto(out *DashboardQuerySpecPluginSpecQuerySpecHaving) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpecQuerySpecHaving.
func (in *DashboardQuerySpecPluginSpecQuerySpecHaving) DeepCopy() *DashboardQuerySpecPluginSpecQuerySpecHaving {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpecQuerySpecHaving)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardQuerySpecPluginSpecQuerySpecLimitBy) DeepCopyInto(out *DashboardQuerySpecPluginSpecQuerySpecLimitBy) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardQuerySpecPluginSpecQuerySpecLimitBy.
func (in *DashboardQuerySpecPluginSpecQuerySpecLimitBy) DeepCopy() *DashboardQuerySpecPluginSpecQuerySpecLimitBy {
	if in == nil {
		return nil
	}
	out := new(DashboardQuerySpecPluginSpecQuerySpecLimitBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSecondaryAggregation) DeepCopyInto(out *DashboardSecondaryAggregation) {
	*out = *in
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]DashboardGroupBy, len(*in))
		copy(*out, *in)
	}
	if in.LimitBy != nil {
		in, out := &in.LimitBy, &out.LimitBy
		*out = new(DashboardSecondaryAggregationLimitBy)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]DashboardOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StepInterval != nil {
		in, out := &in.StepInterval, &out.StepInterval
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSecondaryAggregation.
func (in *DashboardSecondaryAggregation) DeepCopy() *DashboardSecondaryAggregation {
	if in == nil {
		return nil
	}
	out := new(DashboardSecondaryAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSecondaryAggregationLimitBy) DeepCopyInto(out *DashboardSecondaryAggregationLimitBy) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSecondaryAggregationLimitBy.
func (in *DashboardSecondaryAggregationLimitBy) DeepCopy() *DashboardSecondaryAggregationLimitBy {
	if in == nil {
		return nil
	}
	out := new(DashboardSecondaryAggregationLimitBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSelectField) DeepCopyInto(out *DashboardSelectField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSelectField.
func (in *DashboardSelectField) DeepCopy() *DashboardSelectField {
	if in == nil {
		return nil
	}
	out := new(DashboardSelectField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpanGaps) DeepCopyInto(out *DashboardSpanGaps) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpanGaps.
func (in *DashboardSpanGaps) DeepCopy() *DashboardSpanGaps {
	if in == nil {
		return nil
	}
	out := new(DashboardSpanGaps)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpec) DeepCopyInto(out *DashboardSpec) {
	*out = *in
	in.CoreSpec.DeepCopyInto(&out.CoreSpec)
	in.ObjectTemplate.DeepCopyInto(&out.ObjectTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpec.
func (in *DashboardSpec) DeepCopy() *DashboardSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardSpecPayload) DeepCopyInto(out *DashboardSpecPayload) {
	*out = *in
	out.Display = in.Display
	if in.Layouts != nil {
		in, out := &in.Layouts, &out.Layouts
		*out = make([]DashboardLayout, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Panels != nil {
		in, out := &in.Panels, &out.Panels
		*out = make(map[string]DashboardPanel, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]DashboardVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Links != nil {
		in, out := &in.Links, &out.Links
		*out = make([]DashboardLink, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardSpecPayload.
func (in *DashboardSpecPayload) DeepCopy() *DashboardSpecPayload {
	if in == nil {
		return nil
	}
	out := new(DashboardSpecPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardStatus) DeepCopyInto(out *DashboardStatus) {
	*out = *in
	in.CoreStatus.DeepCopyInto(&out.CoreStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardStatus.
func (in *DashboardStatus) DeepCopy() *DashboardStatus {
	if in == nil {
		return nil
	}
	out := new(DashboardStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardTag) DeepCopyInto(out *DashboardTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardTag.
func (in *DashboardTag) DeepCopy() *DashboardTag {
	if in == nil {
		return nil
	}
	out := new(DashboardTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardThreshold) DeepCopyInto(out *DashboardThreshold) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardThreshold.
func (in *DashboardThreshold) DeepCopy() *DashboardThreshold {
	if in == nil {
		return nil
	}
	out := new(DashboardThreshold)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardVariable) DeepCopyInto(out *DashboardVariable) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardVariable.
func (in *DashboardVariable) DeepCopy() *DashboardVariable {
	if in == nil {
		return nil
	}
	out := new(DashboardVariable)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardVariableSpec) DeepCopyInto(out *DashboardVariableSpec) {
	*out = *in
	if in.DefaultValue != nil {
		in, out := &in.DefaultValue, &out.DefaultValue
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.Display != nil {
		in, out := &in.Display, &out.Display
		*out = new(DashboardDisplay)
		**out = **in
	}
	if in.Plugin != nil {
		in, out := &in.Plugin, &out.Plugin
		*out = new(DashboardVariableSpecPlugin)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardVariableSpec.
func (in *DashboardVariableSpec) DeepCopy() *DashboardVariableSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardVariableSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardVariableSpecPlugin) DeepCopyInto(out *DashboardVariableSpecPlugin) {
	*out = *in
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardVariableSpecPlugin.
func (in *DashboardVariableSpecPlugin) DeepCopy() *DashboardVariableSpecPlugin {
	if in == nil {
		return nil
	}
	out := new(DashboardVariableSpecPlugin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardVariableSpecPluginSpec) DeepCopyInto(out *DashboardVariableSpecPluginSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardVariableSpecPluginSpec.
func (in *DashboardVariableSpecPluginSpec) DeepCopy() *DashboardVariableSpecPluginSpec {
	if in == nil {
		return nil
	}
	out := new(DashboardVariableSpecPluginSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DashboardVisualization) DeepCopyInto(out *DashboardVisualization) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DashboardVisualization.
func (in *DashboardVisualization) DeepCopy() *DashboardVisualization {
	if in == nil {
		return nil
	}
	out := new(DashboardVisualization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Endpoint) DeepCopyInto(out *Endpoint) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Endpoint.
func (in *Endpoint) DeepCopy() *Endpoint {
	if in == nil {
		return nil
	}
	out := new(Endpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HeaderAuth) DeepCopyInto(out *HeaderAuth) {
	*out = *in
	if in.ValueFrom != nil {
		in, out := &in.ValueFrom, &out.ValueFrom
		*out = new(ValueSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HeaderAuth.
func (in *HeaderAuth) DeepCopy() *HeaderAuth {
	if in == nil {
		return nil
	}
	out := new(HeaderAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfig) DeepCopyInto(out *ProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfig.
func (in *ProviderConfig) DeepCopy() *ProviderConfig {
	if in == nil {
		return nil
	}
	out := new(ProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigList) DeepCopyInto(out *ProviderConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigList.
func (in *ProviderConfigList) DeepCopy() *ProviderConfigList {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProviderConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigRef) DeepCopyInto(out *ProviderConfigRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigRef.
func (in *ProviderConfigRef) DeepCopy() *ProviderConfigRef {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigSpec) DeepCopyInto(out *ProviderConfigSpec) {
	*out = *in
	in.Endpoint.DeepCopyInto(&out.Endpoint)
	in.Auth.DeepCopyInto(&out.Auth)
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigSpec.
func (in *ProviderConfigSpec) DeepCopy() *ProviderConfigSpec {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProviderConfigStatus) DeepCopyInto(out *ProviderConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedRefVersions != nil {
		in, out := &in.ObservedRefVersions, &out.ObservedRefVersions
		*out = make(map[ProviderConfigObservedRefKind]map[string]string, len(*in))
		for key, val := range *in {
			var outVal map[string]string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProviderConfigStatus.
func (in *ProviderConfigStatus) DeepCopy() *ProviderConfigStatus {
	if in == nil {
		return nil
	}
	out := new(ProviderConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedView) DeepCopyInto(out *SavedView) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedView.
func (in *SavedView) DeepCopy() *SavedView {
	if in == nil {
		return nil
	}
	out := new(SavedView)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SavedView) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewAggregation) DeepCopyInto(out *SavedViewAggregation) {
	*out = *in
	if in.ComparisonSpaceAggregationParam != nil {
		in, out := &in.ComparisonSpaceAggregationParam, &out.ComparisonSpaceAggregationParam
		*out = new(SavedViewComparisonSpaceAggregationParam)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewAggregation.
func (in *SavedViewAggregation) DeepCopy() *SavedViewAggregation {
	if in == nil {
		return nil
	}
	out := new(SavedViewAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewArg) DeepCopyInto(out *SavedViewArg) {
	*out = *in
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewArg.
func (in *SavedViewArg) DeepCopy() *SavedViewArg {
	if in == nil {
		return nil
	}
	out := new(SavedViewArg)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewComparisonSpaceAggregationParam) DeepCopyInto(out *SavedViewComparisonSpaceAggregationParam) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewComparisonSpaceAggregationParam.
func (in *SavedViewComparisonSpaceAggregationParam) DeepCopy() *SavedViewComparisonSpaceAggregationParam {
	if in == nil {
		return nil
	}
	out := new(SavedViewComparisonSpaceAggregationParam)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewDisplay) DeepCopyInto(out *SavedViewDisplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewDisplay.
func (in *SavedViewDisplay) DeepCopy() *SavedViewDisplay {
	if in == nil {
		return nil
	}
	out := new(SavedViewDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewFilter) DeepCopyInto(out *SavedViewFilter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewFilter.
func (in *SavedViewFilter) DeepCopy() *SavedViewFilter {
	if in == nil {
		return nil
	}
	out := new(SavedViewFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewFunction) DeepCopyInto(out *SavedViewFunction) {
	*out = *in
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]SavedViewArg, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewFunction.
func (in *SavedViewFunction) DeepCopy() *SavedViewFunction {
	if in == nil {
		return nil
	}
	out := new(SavedViewFunction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewGroupBy) DeepCopyInto(out *SavedViewGroupBy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewGroupBy.
func (in *SavedViewGroupBy) DeepCopy() *SavedViewGroupBy {
	if in == nil {
		return nil
	}
	out := new(SavedViewGroupBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewHaving) DeepCopyInto(out *SavedViewHaving) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewHaving.
func (in *SavedViewHaving) DeepCopy() *SavedViewHaving {
	if in == nil {
		return nil
	}
	out := new(SavedViewHaving)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewKey) DeepCopyInto(out *SavedViewKey) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewKey.
func (in *SavedViewKey) DeepCopy() *SavedViewKey {
	if in == nil {
		return nil
	}
	out := new(SavedViewKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewLimitBy) DeepCopyInto(out *SavedViewLimitBy) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewLimitBy.
func (in *SavedViewLimitBy) DeepCopy() *SavedViewLimitBy {
	if in == nil {
		return nil
	}
	out := new(SavedViewLimitBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewList) DeepCopyInto(out *SavedViewList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SavedView, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewList.
func (in *SavedViewList) DeepCopy() *SavedViewList {
	if in == nil {
		return nil
	}
	out := new(SavedViewList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SavedViewList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewObjectSpec) DeepCopyInto(out *SavedViewObjectSpec) {
	*out = *in
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewObjectSpec.
func (in *SavedViewObjectSpec) DeepCopy() *SavedViewObjectSpec {
	if in == nil {
		return nil
	}
	out := new(SavedViewObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewObjectTemplate) DeepCopyInto(out *SavedViewObjectTemplate) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SavedViewObjectSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.JSONSpec != nil {
		in, out := &in.JSONSpec, &out.JSONSpec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewObjectTemplate.
func (in *SavedViewObjectTemplate) DeepCopy() *SavedViewObjectTemplate {
	if in == nil {
		return nil
	}
	out := new(SavedViewObjectTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewOrder) DeepCopyInto(out *SavedViewOrder) {
	*out = *in
	if in.Key != nil {
		in, out := &in.Key, &out.Key
		*out = new(SavedViewKey)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewOrder.
func (in *SavedViewOrder) DeepCopy() *SavedViewOrder {
	if in == nil {
		return nil
	}
	out := new(SavedViewOrder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewQuery) DeepCopyInto(out *SavedViewQuery) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(SavedViewQuerySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewQuery.
func (in *SavedViewQuery) DeepCopy() *SavedViewQuery {
	if in == nil {
		return nil
	}
	out := new(SavedViewQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewQuerySpec) DeepCopyInto(out *SavedViewQuerySpec) {
	*out = *in
	if in.Aggregations != nil {
		in, out := &in.Aggregations, &out.Aggregations
		*out = make([]SavedViewAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Filter != nil {
		in, out := &in.Filter, &out.Filter
		*out = new(SavedViewFilter)
		**out = **in
	}
	if in.Functions != nil {
		in, out := &in.Functions, &out.Functions
		*out = make([]SavedViewFunction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]SavedViewGroupBy, len(*in))
		copy(*out, *in)
	}
	if in.Having != nil {
		in, out := &in.Having, &out.Having
		*out = new(SavedViewHaving)
		**out = **in
	}
	if in.LimitBy != nil {
		in, out := &in.LimitBy, &out.LimitBy
		*out = new(SavedViewLimitBy)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]SavedViewOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecondaryAggregations != nil {
		in, out := &in.SecondaryAggregations, &out.SecondaryAggregations
		*out = make([]SavedViewSecondaryAggregation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SelectFields != nil {
		in, out := &in.SelectFields, &out.SelectFields
		*out = make([]SavedViewSelectField, len(*in))
		copy(*out, *in)
	}
	if in.Step != nil {
		in, out := &in.Step, &out.Step
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
	if in.StepInterval != nil {
		in, out := &in.StepInterval, &out.StepInterval
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewQuerySpec.
func (in *SavedViewQuerySpec) DeepCopy() *SavedViewQuerySpec {
	if in == nil {
		return nil
	}
	out := new(SavedViewQuerySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewSecondaryAggregation) DeepCopyInto(out *SavedViewSecondaryAggregation) {
	*out = *in
	if in.GroupBy != nil {
		in, out := &in.GroupBy, &out.GroupBy
		*out = make([]SavedViewGroupBy, len(*in))
		copy(*out, *in)
	}
	if in.LimitBy != nil {
		in, out := &in.LimitBy, &out.LimitBy
		*out = new(SavedViewSecondaryAggregationLimitBy)
		(*in).DeepCopyInto(*out)
	}
	if in.Order != nil {
		in, out := &in.Order, &out.Order
		*out = make([]SavedViewOrder, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.StepInterval != nil {
		in, out := &in.StepInterval, &out.StepInterval
		*out = new(apiextensionsv1.JSON)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewSecondaryAggregation.
func (in *SavedViewSecondaryAggregation) DeepCopy() *SavedViewSecondaryAggregation {
	if in == nil {
		return nil
	}
	out := new(SavedViewSecondaryAggregation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewSecondaryAggregationLimitBy) DeepCopyInto(out *SavedViewSecondaryAggregationLimitBy) {
	*out = *in
	if in.Keys != nil {
		in, out := &in.Keys, &out.Keys
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewSecondaryAggregationLimitBy.
func (in *SavedViewSecondaryAggregationLimitBy) DeepCopy() *SavedViewSecondaryAggregationLimitBy {
	if in == nil {
		return nil
	}
	out := new(SavedViewSecondaryAggregationLimitBy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewSelectField) DeepCopyInto(out *SavedViewSelectField) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewSelectField.
func (in *SavedViewSelectField) DeepCopy() *SavedViewSelectField {
	if in == nil {
		return nil
	}
	out := new(SavedViewSelectField)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewSpec) DeepCopyInto(out *SavedViewSpec) {
	*out = *in
	in.CoreSpec.DeepCopyInto(&out.CoreSpec)
	in.ObjectTemplate.DeepCopyInto(&out.ObjectTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewSpec.
func (in *SavedViewSpec) DeepCopy() *SavedViewSpec {
	if in == nil {
		return nil
	}
	out := new(SavedViewSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewSpecPayload) DeepCopyInto(out *SavedViewSpecPayload) {
	*out = *in
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]SavedViewQuery, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Display != nil {
		in, out := &in.Display, &out.Display
		*out = new(SavedViewDisplay)
		**out = **in
	}
	if in.SelectedFields != nil {
		in, out := &in.SelectedFields, &out.SelectedFields
		*out = make([]SavedViewSelectField, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewSpecPayload.
func (in *SavedViewSpecPayload) DeepCopy() *SavedViewSpecPayload {
	if in == nil {
		return nil
	}
	out := new(SavedViewSpecPayload)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SavedViewStatus) DeepCopyInto(out *SavedViewStatus) {
	*out = *in
	in.CoreStatus.DeepCopyInto(&out.CoreStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SavedViewStatus.
func (in *SavedViewStatus) DeepCopy() *SavedViewStatus {
	if in == nil {
		return nil
	}
	out := new(SavedViewStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SigNozResource) DeepCopyInto(out *SigNozResource) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SigNozResource.
func (in *SigNozResource) DeepCopy() *SigNozResource {
	if in == nil {
		return nil
	}
	out := new(SigNozResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
	if in.CASecretRef != nil {
		in, out := &in.CASecretRef, &out.CASecretRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserObjectSpec) DeepCopyInto(out *UserObjectSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserObjectSpec.
func (in *UserObjectSpec) DeepCopy() *UserObjectSpec {
	if in == nil {
		return nil
	}
	out := new(UserObjectSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserObjectTemplate) DeepCopyInto(out *UserObjectTemplate) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(UserObjectSpec)
		**out = **in
	}
	if in.JSONSpec != nil {
		in, out := &in.JSONSpec, &out.JSONSpec
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserObjectTemplate.
func (in *UserObjectTemplate) DeepCopy() *UserObjectTemplate {
	if in == nil {
		return nil
	}
	out := new(UserObjectTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpec) DeepCopyInto(out *UserSpec) {
	*out = *in
	in.CoreSpec.DeepCopyInto(&out.CoreSpec)
	in.ObjectTemplate.DeepCopyInto(&out.ObjectTemplate)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpec.
func (in *UserSpec) DeepCopy() *UserSpec {
	if in == nil {
		return nil
	}
	out := new(UserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStatus) DeepCopyInto(out *UserStatus) {
	*out = *in
	in.CoreStatus.DeepCopyInto(&out.CoreStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStatus.
func (in *UserStatus) DeepCopy() *UserStatus {
	if in == nil {
		return nil
	}
	out := new(UserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSource) DeepCopyInto(out *ValueSource) {
	*out = *in
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(corev1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(corev1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSource.
func (in *ValueSource) DeepCopy() *ValueSource {
	if in == nil {
		return nil
	}
	out := new(ValueSource)
	in.DeepCopyInto(out)
	return out
}
