// Code generated by skaff operator types DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type RuleObjectSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Alert string `json:"alert"`

	// +kubebuilder:validation:Enum=METRIC_BASED_ALERT;TRACES_BASED_ALERT;LOGS_BASED_ALERT;EXCEPTIONS_BASED_ALERT
	// +kubebuilder:validation:Required
	AlertType string `json:"alertType"`

	// +kubebuilder:validation:Required
	Condition RuleCondition `json:"condition"`

	// +kubebuilder:validation:Required
	Evaluation RuleEvaluation `json:"evaluation"`

	// +kubebuilder:validation:Required
	NotificationSettings RuleNotificationSettings `json:"notificationSettings"`

	// +kubebuilder:validation:Enum=threshold_rule;promql_rule;anomaly_rule
	// +kubebuilder:validation:Required
	RuleType string `json:"ruleType"`

	// +kubebuilder:validation:Enum=v2alpha1
	// +kubebuilder:validation:Required
	SchemaVersion string `json:"schemaVersion"`

	// +optional
	Annotations map[string]string `json:"annotations,omitempty"`

	// +optional
	Description string `json:"description,omitempty"`

	// +optional
	Disabled bool `json:"disabled,omitempty"`

	// +optional
	Labels map[string]string `json:"labels,omitempty"`
}

type RuleCondition struct {
	// +kubebuilder:validation:Required
	CompositeQuery RuleCompositeQuery `json:"compositeQuery"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	SelectedQueryName string `json:"selectedQueryName"`

	// +kubebuilder:validation:Required
	Thresholds RuleThresholds `json:"thresholds"`

	// +optional
	AbsentFor int64 `json:"absentFor,omitempty"`

	// +optional
	AlertOnAbsent bool `json:"alertOnAbsent,omitempty"`

	// +optional
	Algorithm string `json:"algorithm,omitempty"`

	// +optional
	RequireMinPoints bool `json:"requireMinPoints,omitempty"`

	// +optional
	RequiredNumPoints int64 `json:"requiredNumPoints,omitempty"`

	// +kubebuilder:validation:Enum=hourly;daily;weekly
	// +optional
	Seasonality string `json:"seasonality,omitempty"`
}

type RuleCompositeQuery struct {
	// +kubebuilder:validation:Enum=value;table;graph
	// +kubebuilder:validation:Required
	PanelType string `json:"panelType"`

	// +kubebuilder:validation:Required
	Queries []RuleQuery `json:"queries"`

	// +kubebuilder:validation:Enum=builder;clickhouse_sql;promql
	// +kubebuilder:validation:Required
	QueryType string `json:"queryType"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.type != 'builder_query' || !has(self.spec) || has(self.spec.signal)",message="type builder_query requires spec.signal"
// +kubebuilder:validation:XValidation:rule="self.type != 'builder_ai_query' || !has(self.spec) || has(self.spec.signal)",message="type builder_ai_query requires spec.signal"
type RuleQuery struct {
	// +kubebuilder:validation:Enum=builder_query;builder_ai_query;builder_formula;builder_trace_operator;promql;clickhouse_sql
	// +kubebuilder:validation:Required
	Type string `json:"type"`

	// +optional
	Spec *RuleQuerySpec `json:"spec,omitempty"`
}

type RuleQuerySpec struct {
	// +optional
	Aggregations []RuleAggregation `json:"aggregations,omitempty"`

	// +optional
	Cursor string `json:"cursor,omitempty"`

	// +optional
	Disabled bool `json:"disabled,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	Filter *RuleFilter `json:"filter,omitempty"`

	// +optional
	Functions []RuleFunction `json:"functions,omitempty"`

	// +optional
	GroupBy []RuleGroupBy `json:"groupBy,omitempty"`

	// +optional
	Having *RuleHaving `json:"having,omitempty"`

	// +optional
	Legend string `json:"legend,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *RuleLimitBy `json:"limitBy,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	Offset int64 `json:"offset,omitempty"`

	// +optional
	Order []RuleOrder `json:"order,omitempty"`

	// +optional
	Query string `json:"query,omitempty"`

	// +optional
	ReturnSpansFrom string `json:"returnSpansFrom,omitempty"`

	// +optional
	SecondaryAggregations []RuleSecondaryAggregation `json:"secondaryAggregations,omitempty"`

	// +optional
	SelectFields []RuleSelectField `json:"selectFields,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +kubebuilder:validation:Enum=meter
	// +optional
	Source string `json:"source,omitempty"`

	// +optional
	Stats bool `json:"stats,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Step *apiextensionsv1.JSON `json:"step,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type RuleAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	ComparisonSpaceAggregationParam *RuleComparisonSpaceAggregationParam `json:"comparisonSpaceAggregationParam,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	MetricName string `json:"metricName,omitempty"`

	// +kubebuilder:validation:Enum=sum;count;avg;min;max;last;median
	// +optional
	ReduceTo string `json:"reduceTo,omitempty"`

	// +kubebuilder:validation:Enum=sum;avg;min;max;count;p50;p75;p90;p95;p99
	// +optional
	SpaceAggregation string `json:"spaceAggregation,omitempty"`

	// +kubebuilder:validation:Enum=delta;cumulative;unspecified
	// +optional
	Temporality string `json:"temporality,omitempty"`

	// +kubebuilder:validation:Enum=latest;sum;avg;min;max;count;count_distinct;rate;increase
	// +optional
	TimeAggregation string `json:"timeAggregation,omitempty"`
}

type RuleComparisonSpaceAggregationParam struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Operator string `json:"operator"`

	// +kubebuilder:validation:Required
	Threshold float64 `json:"threshold"`
}

type RuleFilter struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type RuleFunction struct {
	// +optional
	Args []RuleArg `json:"args,omitempty"`

	// +kubebuilder:validation:Enum=cutoffmin;cutoffmax;clampmin;clampmax;absolute;runningdiff;log2;log10;cumulativesum;ewma3;ewma5;ewma7;median3;median5;median7;timeshift;anomaly;fillzero
	// +optional
	Name string `json:"name,omitempty"`
}

type RuleArg struct {
	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Value *apiextensionsv1.JSON `json:"value,omitempty"`
}

type RuleGroupBy struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;trace;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type RuleHaving struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type RuleLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type RuleOrder struct {
	// +kubebuilder:validation:Enum=asc;desc
	// +optional
	Direction string `json:"direction,omitempty"`

	// +optional
	Key *RuleKey `json:"key,omitempty"`
}

type RuleKey struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;trace;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type RuleSecondaryAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	GroupBy []RuleGroupBy `json:"groupBy,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *RuleSecondaryAggregationLimitBy `json:"limitBy,omitempty"`

	// +optional
	Order []RuleOrder `json:"order,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type RuleSecondaryAggregationLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type RuleSelectField struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;trace;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type RuleThresholds struct {
	// +kubebuilder:validation:Enum=basic
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec []RuleThresholdsSpec `json:"spec"`
}

type RuleThresholdsSpec struct {
	// +kubebuilder:validation:Enum=at_least_once;all_the_times;on_average;in_total;last
	// +kubebuilder:validation:Required
	MatchType string `json:"matchType"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +kubebuilder:validation:Enum=above;below;equal;not_equal;above_or_equal;below_or_equal;outside_bounds
	// +kubebuilder:validation:Required
	Op string `json:"op"`

	// +kubebuilder:validation:Required
	Target float64 `json:"target"`

	// +optional
	Channels []string `json:"channels,omitempty"`

	// +optional
	RecoveryTarget float64 `json:"recoveryTarget,omitempty"`

	// +optional
	TargetUnit string `json:"targetUnit,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.kind != 'rolling' || (has(self.spec.evalWindow) && has(self.spec.frequency))",message="kind rolling requires spec.evalWindow, spec.frequency"
// +kubebuilder:validation:XValidation:rule="self.kind != 'cumulative' || (has(self.spec.schedule) && has(self.spec.frequency) && has(self.spec.timezone))",message="kind cumulative requires spec.schedule, spec.frequency, spec.timezone"
type RuleEvaluation struct {
	// +kubebuilder:validation:Enum=rolling;cumulative
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec RuleEvaluationSpec `json:"spec"`
}

type RuleEvaluationSpec struct {
	// +optional
	EvalWindow string `json:"evalWindow,omitempty"`

	// +optional
	Frequency string `json:"frequency,omitempty"`

	// +optional
	Schedule *RuleSchedule `json:"schedule,omitempty"`

	// +optional
	Timezone string `json:"timezone,omitempty"`
}

type RuleSchedule struct {
	// +kubebuilder:validation:Enum=hourly;daily;weekly;monthly
	// +kubebuilder:validation:Required
	Type string `json:"type"`

	// +optional
	Day int64 `json:"day,omitempty"`

	// +optional
	Hour int64 `json:"hour,omitempty"`

	// +optional
	Minute int64 `json:"minute,omitempty"`

	// +optional
	Weekday int64 `json:"weekday,omitempty"`
}

type RuleNotificationSettings struct {
	// +optional
	GroupBy []string `json:"groupBy,omitempty"`

	// +optional
	NewGroupEvalDelay string `json:"newGroupEvalDelay,omitempty"`

	// +optional
	Renotify *RuleRenotify `json:"renotify,omitempty"`

	// +optional
	UsePolicy bool `json:"usePolicy,omitempty"`
}

type RuleRenotify struct {
	// +optional
	AlertStates []string `json:"alertStates,omitempty"`

	// +optional
	Enabled bool `json:"enabled,omitempty"`

	// +optional
	Interval string `json:"interval,omitempty"`
}

// +kubebuilder:validation:MinProperties=1
// +kubebuilder:validation:MaxProperties=1
type RuleObjectTemplate struct {
	// +optional
	Spec *RuleObjectSpec `json:"spec,omitempty"`

	// +optional
	// +kubebuilder:validation:MinLength=1
	JSONSpec *string `json:"jsonSpec,omitempty"`
}

type RuleSpec struct {
	CoreSpec `json:",inline"`

	// +kubebuilder:validation:Required
	ObjectTemplate RuleObjectTemplate `json:"objectTemplate"`
}

type RuleStatus struct {
	CoreStatus `json:",inline"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="ID",type=string,JSONPath=".status.signozResource.id"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

type Rule struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec RuleSpec `json:"spec"`

	// +optional
	Status RuleStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type RuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []Rule `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &Rule{}, &RuleList{})
		return nil
	})
}
