// Code generated by skaff operator types DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type DashboardObjectSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	SchemaVersion string `json:"schemaVersion"`

	// +kubebuilder:validation:Required
	Spec DashboardSpecPayload `json:"spec"`

	// +kubebuilder:validation:Required
	Tags []DashboardTag `json:"tags"`

	// +optional
	Image string `json:"image,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`
}

type DashboardSpecPayload struct {
	// +kubebuilder:validation:Required
	Display DashboardDisplay `json:"display"`

	// +kubebuilder:validation:Required
	Layouts []DashboardLayout `json:"layouts"`

	// +kubebuilder:validation:Required
	Panels map[string]DashboardPanel `json:"panels"`

	// +kubebuilder:validation:Required
	Variables []DashboardVariable `json:"variables"`

	// +optional
	Duration string `json:"duration,omitempty"`

	// +optional
	Links []DashboardLink `json:"links,omitempty"`

	// +optional
	RefreshInterval string `json:"refreshInterval,omitempty"`
}

type DashboardDisplay struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`
}

type DashboardLayout struct {
	// +kubebuilder:validation:Enum=Grid
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardLayoutSpec `json:"spec"`
}

type DashboardLayoutSpec struct {
	// +optional
	Display *DashboardLayoutSpecDisplay `json:"display,omitempty"`

	// +optional
	Items []DashboardItem `json:"items,omitempty"`

	// +optional
	RepeatVariable string `json:"repeatVariable,omitempty"`
}

type DashboardLayoutSpecDisplay struct {
	// +optional
	Collapse *DashboardCollapse `json:"collapse,omitempty"`

	// +optional
	Title string `json:"title,omitempty"`
}

type DashboardCollapse struct {
	// +optional
	Open bool `json:"open,omitempty"`
}

type DashboardItem struct {
	// +optional
	Content *DashboardContent `json:"content,omitempty"`

	// +optional
	Height int64 `json:"height,omitempty"`

	// +optional
	Width int64 `json:"width,omitempty"`

	// +optional
	X int64 `json:"x,omitempty"`

	// +optional
	Y int64 `json:"y,omitempty"`
}

type DashboardContent struct {
	// +optional
	Ref string `json:"$ref,omitempty"`
}

type DashboardPanel struct {
	// +kubebuilder:validation:Enum=Panel
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardPanelSpec `json:"spec"`
}

type DashboardPanelSpec struct {
	// +kubebuilder:validation:Required
	Display DashboardDisplay `json:"display"`

	// +kubebuilder:validation:Required
	Plugin DashboardPlugin `json:"plugin"`

	// +kubebuilder:validation:Required
	Queries []DashboardQuery `json:"queries"`

	// +optional
	Links []DashboardLink `json:"links,omitempty"`
}

type DashboardPlugin struct {
	// +kubebuilder:validation:Enum=signoz/TimeSeriesPanel;signoz/BarChartPanel;signoz/NumberPanel;signoz/PieChartPanel;signoz/TablePanel;signoz/HistogramPanel;signoz/ListPanel
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardPluginSpec `json:"spec"`
}

type DashboardPluginSpec struct {
	// +optional
	Axes *DashboardAxes `json:"axes,omitempty"`

	// +optional
	ChartAppearance *DashboardChartAppearance `json:"chartAppearance,omitempty"`

	// +optional
	Formatting *DashboardFormatting `json:"formatting,omitempty"`

	// +optional
	HistogramBuckets *DashboardHistogramBuckets `json:"histogramBuckets,omitempty"`

	// +optional
	Legend *DashboardLegend `json:"legend,omitempty"`

	// +optional
	SelectFields []DashboardSelectField `json:"selectFields,omitempty"`

	// +optional
	Thresholds []DashboardThreshold `json:"thresholds,omitempty"`

	// +optional
	Visualization *DashboardVisualization `json:"visualization,omitempty"`
}

type DashboardAxes struct {
	// +optional
	IsLogScale bool `json:"isLogScale,omitempty"`

	// +optional
	SoftMax float64 `json:"softMax,omitempty"`

	// +optional
	SoftMin float64 `json:"softMin,omitempty"`
}

type DashboardChartAppearance struct {
	// +kubebuilder:validation:Enum=solid;gradient;none
	// +optional
	FillMode string `json:"fillMode,omitempty"`

	// +kubebuilder:validation:Enum=linear;spline;step_after;step_before
	// +optional
	LineInterpolation string `json:"lineInterpolation,omitempty"`

	// +kubebuilder:validation:Enum=solid;dashed
	// +optional
	LineStyle string `json:"lineStyle,omitempty"`

	// +optional
	ShowPoints bool `json:"showPoints,omitempty"`

	// +optional
	SpanGaps *DashboardSpanGaps `json:"spanGaps,omitempty"`
}

type DashboardSpanGaps struct {
	// +optional
	FillLessThan string `json:"fillLessThan,omitempty"`

	// +optional
	FillOnlyBelow bool `json:"fillOnlyBelow,omitempty"`
}

type DashboardFormatting struct {
	// +optional
	ColumnUnits map[string]string `json:"columnUnits,omitempty"`

	// +kubebuilder:validation:Enum=0;1;2;3;4;full
	// +optional
	DecimalPrecision string `json:"decimalPrecision,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type DashboardHistogramBuckets struct {
	// +optional
	BucketCount float64 `json:"bucketCount,omitempty"`

	// +optional
	BucketWidth float64 `json:"bucketWidth,omitempty"`

	// +optional
	MergeAllActiveQueries bool `json:"mergeAllActiveQueries,omitempty"`
}

type DashboardLegend struct {
	// +optional
	CustomColors map[string]string `json:"customColors,omitempty"`

	// +kubebuilder:validation:Enum=list
	// +optional
	Mode string `json:"mode,omitempty"`

	// +kubebuilder:validation:Enum=bottom;right
	// +optional
	Position string `json:"position,omitempty"`
}

type DashboardSelectField struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type DashboardThreshold struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Color string `json:"color"`

	// +kubebuilder:validation:Required
	Value float64 `json:"value"`

	// +optional
	ColumnName string `json:"columnName,omitempty"`

	// +kubebuilder:validation:Enum=text;background
	// +optional
	Format string `json:"format,omitempty"`

	// +optional
	Label string `json:"label,omitempty"`

	// +kubebuilder:validation:Enum=above;below;above_or_equal;below_or_equal;equal;not_equal
	// +optional
	Operator string `json:"operator,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type DashboardVisualization struct {
	// +optional
	FillSpans bool `json:"fillSpans,omitempty"`

	// +optional
	StackedBarChart bool `json:"stackedBarChart,omitempty"`

	// +kubebuilder:validation:Enum=global_time;last_5_min;last_15_min;last_30_min;last_1_hr;last_6_hr;last_1_day;last_3_days;last_1_week;last_1_month
	// +optional
	TimePreference string `json:"timePreference,omitempty"`
}

type DashboardQuery struct {
	// +kubebuilder:validation:Enum=scalar;time_series;raw;raw_stream;trace
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardQuerySpec `json:"spec"`
}

type DashboardQuerySpec struct {
	// +kubebuilder:validation:Required
	Plugin DashboardQuerySpecPlugin `json:"plugin"`

	// +optional
	Name string `json:"name,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.kind != 'signoz/BuilderQuery' || has(self.spec.signal)",message="kind signoz/BuilderQuery requires spec.signal"
type DashboardQuerySpecPlugin struct {
	// +kubebuilder:validation:Enum=signoz/BuilderQuery;signoz/CompositeQuery;signoz/Formula;signoz/PromQLQuery;signoz/ClickHouseSQL;signoz/TraceOperator
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardQuerySpecPluginSpec `json:"spec"`
}

type DashboardQuerySpecPluginSpec struct {
	// +optional
	Aggregations []DashboardAggregation `json:"aggregations,omitempty"`

	// +optional
	Cursor string `json:"cursor,omitempty"`

	// +optional
	Disabled bool `json:"disabled,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	Filter *DashboardFilter `json:"filter,omitempty"`

	// +optional
	Functions []DashboardFunction `json:"functions,omitempty"`

	// +optional
	GroupBy []DashboardGroupBy `json:"groupBy,omitempty"`

	// +optional
	Having *DashboardHaving `json:"having,omitempty"`

	// +optional
	Legend string `json:"legend,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *DashboardLimitBy `json:"limitBy,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	Offset int64 `json:"offset,omitempty"`

	// +optional
	Order []DashboardOrder `json:"order,omitempty"`

	// +optional
	Queries []DashboardQuerySpecPluginSpecQuery `json:"queries,omitempty"`

	// +optional
	Query string `json:"query,omitempty"`

	// +optional
	ReturnSpansFrom string `json:"returnSpansFrom,omitempty"`

	// +optional
	SecondaryAggregations []DashboardSecondaryAggregation `json:"secondaryAggregations,omitempty"`

	// +optional
	SelectFields []DashboardSelectField `json:"selectFields,omitempty"`

	// +kubebuilder:validation:Enum=logs;metrics;traces
	// +optional
	Signal string `json:"signal,omitempty"`

	// +kubebuilder:validation:Enum=meter
	// +optional
	Source string `json:"source,omitempty"`

	// +optional
	Stats bool `json:"stats,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Step *apiextensionsv1.JSON `json:"step,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type DashboardAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	ComparisonSpaceAggregationParam *DashboardComparisonSpaceAggregationParam `json:"comparisonSpaceAggregationParam,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	MetricName string `json:"metricName,omitempty"`

	// +kubebuilder:validation:Enum=sum;count;avg;min;max;last;median
	// +optional
	ReduceTo string `json:"reduceTo,omitempty"`

	// +kubebuilder:validation:Enum=sum;avg;min;max;count;p50;p75;p90;p95;p99
	// +optional
	SpaceAggregation string `json:"spaceAggregation,omitempty"`

	// +kubebuilder:validation:Enum=delta;cumulative;unspecified
	// +optional
	Temporality string `json:"temporality,omitempty"`

	// +kubebuilder:validation:Enum=latest;sum;avg;min;max;count;count_distinct;rate;increase
	// +optional
	TimeAggregation string `json:"timeAggregation,omitempty"`
}

type DashboardComparisonSpaceAggregationParam struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Operator string `json:"operator"`

	// +kubebuilder:validation:Required
	Threshold float64 `json:"threshold"`
}

type DashboardFilter struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type DashboardFunction struct {
	// +optional
	Args []DashboardArg `json:"args,omitempty"`

	// +kubebuilder:validation:Enum=cutoffmin;cutoffmax;clampmin;clampmax;absolute;runningdiff;log2;log10;cumulativesum;ewma3;ewma5;ewma7;median3;median5;median7;timeshift;anomaly;fillzero
	// +optional
	Name string `json:"name,omitempty"`
}

type DashboardArg struct {
	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Value *apiextensionsv1.JSON `json:"value,omitempty"`
}

type DashboardGroupBy struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type DashboardHaving struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type DashboardLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type DashboardOrder struct {
	// +kubebuilder:validation:Enum=asc;desc
	// +optional
	Direction string `json:"direction,omitempty"`

	// +optional
	Key *DashboardKey `json:"key,omitempty"`
}

type DashboardKey struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.type != 'builder_query' || !has(self.spec) || has(self.spec.signal)",message="type builder_query requires spec.signal"
// +kubebuilder:validation:XValidation:rule="self.type != 'builder_ai_query' || !has(self.spec) || has(self.spec.signal)",message="type builder_ai_query requires spec.signal"
type DashboardQuerySpecPluginSpecQuery struct {
	// +kubebuilder:validation:Enum=builder_query;builder_ai_query;builder_formula;builder_trace_operator;promql;clickhouse_sql
	// +kubebuilder:validation:Required
	Type string `json:"type"`

	// +optional
	Spec *DashboardQuerySpecPluginSpecQuerySpec `json:"spec,omitempty"`
}

type DashboardQuerySpecPluginSpecQuerySpec struct {
	// +optional
	Aggregations []DashboardQuerySpecPluginSpecQuerySpecAggregation `json:"aggregations,omitempty"`

	// +optional
	Cursor string `json:"cursor,omitempty"`

	// +optional
	Disabled bool `json:"disabled,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	Filter *DashboardQuerySpecPluginSpecQuerySpecFilter `json:"filter,omitempty"`

	// +optional
	Functions []DashboardFunction `json:"functions,omitempty"`

	// +optional
	GroupBy []DashboardGroupBy `json:"groupBy,omitempty"`

	// +optional
	Having *DashboardQuerySpecPluginSpecQuerySpecHaving `json:"having,omitempty"`

	// +optional
	Legend string `json:"legend,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *DashboardQuerySpecPluginSpecQuerySpecLimitBy `json:"limitBy,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	Offset int64 `json:"offset,omitempty"`

	// +optional
	Order []DashboardOrder `json:"order,omitempty"`

	// +optional
	Query string `json:"query,omitempty"`

	// +optional
	ReturnSpansFrom string `json:"returnSpansFrom,omitempty"`

	// +optional
	SecondaryAggregations []DashboardSecondaryAggregation `json:"secondaryAggregations,omitempty"`

	// +optional
	SelectFields []DashboardSelectField `json:"selectFields,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +kubebuilder:validation:Enum=meter
	// +optional
	Source string `json:"source,omitempty"`

	// +optional
	Stats bool `json:"stats,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Step *apiextensionsv1.JSON `json:"step,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type DashboardQuerySpecPluginSpecQuerySpecAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	ComparisonSpaceAggregationParam *DashboardComparisonSpaceAggregationParam `json:"comparisonSpaceAggregationParam,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	MetricName string `json:"metricName,omitempty"`

	// +kubebuilder:validation:Enum=sum;count;avg;min;max;last;median
	// +optional
	ReduceTo string `json:"reduceTo,omitempty"`

	// +kubebuilder:validation:Enum=sum;avg;min;max;count;p50;p75;p90;p95;p99
	// +optional
	SpaceAggregation string `json:"spaceAggregation,omitempty"`

	// +kubebuilder:validation:Enum=delta;cumulative;unspecified
	// +optional
	Temporality string `json:"temporality,omitempty"`

	// +kubebuilder:validation:Enum=latest;sum;avg;min;max;count;count_distinct;rate;increase
	// +optional
	TimeAggregation string `json:"timeAggregation,omitempty"`
}

type DashboardQuerySpecPluginSpecQuerySpecFilter struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type DashboardQuerySpecPluginSpecQuerySpecHaving struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type DashboardQuerySpecPluginSpecQuerySpecLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type DashboardSecondaryAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	GroupBy []DashboardGroupBy `json:"groupBy,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *DashboardSecondaryAggregationLimitBy `json:"limitBy,omitempty"`

	// +optional
	Order []DashboardOrder `json:"order,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type DashboardSecondaryAggregationLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type DashboardLink struct {
	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	RenderVariables bool `json:"renderVariables,omitempty"`

	// +optional
	TargetBlank bool `json:"targetBlank,omitempty"`

	// +optional
	Tooltip string `json:"tooltip,omitempty"`

	// +optional
	Url string `json:"url,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.kind != 'ListVariable' || (has(self.spec.display) && has(self.spec.name))",message="kind ListVariable requires spec.display, spec.name"
// +kubebuilder:validation:XValidation:rule="self.kind != 'TextVariable' || (has(self.spec.display) && has(self.spec.value) && has(self.spec.name))",message="kind TextVariable requires spec.display, spec.value, spec.name"
type DashboardVariable struct {
	// +kubebuilder:validation:Enum=ListVariable;TextVariable
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardVariableSpec `json:"spec"`
}

type DashboardVariableSpec struct {
	// +optional
	AllowAllValue bool `json:"allowAllValue,omitempty"`

	// +optional
	AllowMultiple bool `json:"allowMultiple,omitempty"`

	// +optional
	CapturingRegexp string `json:"capturingRegexp,omitempty"`

	// +optional
	Constant bool `json:"constant,omitempty"`

	// +optional
	CustomAllValue string `json:"customAllValue,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	DefaultValue *apiextensionsv1.JSON `json:"defaultValue,omitempty"`

	// +optional
	Display *DashboardDisplay `json:"display,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	Plugin *DashboardVariableSpecPlugin `json:"plugin,omitempty"`

	// +kubebuilder:validation:Enum=none;alphabetical-asc;alphabetical-desc;numerical-asc;numerical-desc;alphabetical-ci-asc;alphabetical-ci-desc
	// +optional
	Sort string `json:"sort,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.kind != 'signoz/DynamicVariable' || (has(self.spec.name) && has(self.spec.signal))",message="kind signoz/DynamicVariable requires spec.name, spec.signal"
// +kubebuilder:validation:XValidation:rule="self.kind != 'signoz/QueryVariable' || has(self.spec.queryValue)",message="kind signoz/QueryVariable requires spec.queryValue"
// +kubebuilder:validation:XValidation:rule="self.kind != 'signoz/CustomVariable' || has(self.spec.customValue)",message="kind signoz/CustomVariable requires spec.customValue"
type DashboardVariableSpecPlugin struct {
	// +kubebuilder:validation:Enum=signoz/DynamicVariable;signoz/QueryVariable;signoz/CustomVariable
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Required
	Spec DashboardVariableSpecPluginSpec `json:"spec"`
}

type DashboardVariableSpecPluginSpec struct {
	// +optional
	CustomValue string `json:"customValue,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	QueryValue string `json:"queryValue,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics;all
	// +optional
	Signal string `json:"signal,omitempty"`
}

type DashboardTag struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Key string `json:"key"`

	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Value string `json:"value"`
}

// +kubebuilder:validation:MinProperties=1
// +kubebuilder:validation:MaxProperties=1
type DashboardObjectTemplate struct {
	// +optional
	Spec *DashboardObjectSpec `json:"spec,omitempty"`

	// +optional
	// +kubebuilder:validation:MinLength=1
	JSONSpec *string `json:"jsonSpec,omitempty"`
}

type DashboardSpec struct {
	CoreSpec `json:",inline"`

	// +kubebuilder:validation:Required
	ObjectTemplate DashboardObjectTemplate `json:"objectTemplate"`
}

type DashboardStatus struct {
	CoreStatus `json:",inline"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="ID",type=string,JSONPath=".status.signozResource.id"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

type Dashboard struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec DashboardSpec `json:"spec"`

	// +optional
	Status DashboardStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type DashboardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []Dashboard `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &Dashboard{}, &DashboardList{})
		return nil
	})
}
