// Code generated by skaff operator types DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type RoleObjectSpec struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +optional
	TransactionGroups []RoleTransactionGroup `json:"transactionGroups,omitempty"`
}

type RoleTransactionGroup struct {
	// +kubebuilder:validation:Required
	ObjectGroup RoleObjectGroup `json:"objectGroup"`

	// +kubebuilder:validation:Enum=create;read;update;delete;list;assignee;attach;detach
	// +kubebuilder:validation:Required
	Relation string `json:"relation"`
}

type RoleObjectGroup struct {
	// +kubebuilder:validation:Required
	Resource RoleResource `json:"resource"`

	// +kubebuilder:validation:Required
	Selectors []string `json:"selectors"`
}

type RoleResource struct {
	// +kubebuilder:validation:Enum=anonymous;organization;role;serviceaccount;user;notification-channel;route-policy;apdex-setting;auth-domain;session;cloud-integration;cloud-integration-service;integration;dashboard;public-dashboard;ingestion-key;ingestion-limit;pipeline;user-preference;org-preference;quick-filter;ttl-setting;rule;planned-maintenance;saved-view;trace-funnel;factor-password;factor-api-key;license;subscription;logs;traces;metrics;audit-logs;meter-metrics;logs-field;traces-field
	// +kubebuilder:validation:Required
	Kind string `json:"kind"`

	// +kubebuilder:validation:Enum=user;serviceaccount;anonymous;role;organization;metaresource;telemetryresource
	// +kubebuilder:validation:Required
	Type string `json:"type"`
}

// +kubebuilder:validation:MinProperties=1
// +kubebuilder:validation:MaxProperties=1
type RoleObjectTemplate struct {
	// +optional
	Spec *RoleObjectSpec `json:"spec,omitempty"`

	// +optional
	// +kubebuilder:validation:MinLength=1
	JSONSpec *string `json:"jsonSpec,omitempty"`
}

type RoleSpec struct {
	CoreSpec `json:",inline"`

	// +kubebuilder:validation:Required
	ObjectTemplate RoleObjectTemplate `json:"objectTemplate"`
}

type RoleStatus struct {
	CoreStatus `json:",inline"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="ID",type=string,JSONPath=".status.signozResource.id"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

type Role struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec RoleSpec `json:"spec"`

	// +optional
	Status RoleStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type RoleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []Role `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &Role{}, &RoleList{})
		return nil
	})
}
