// Code generated by skaff operator types DO NOT EDIT.

package v1alpha1

import (
	apiextensionsv1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

type SavedViewObjectSpec struct {
	// +kubebuilder:validation:Enum=v2
	// +kubebuilder:validation:Required
	SchemaVersion string `json:"schemaVersion"`

	// +kubebuilder:validation:Enum=traces;logs;metrics;meter
	// +kubebuilder:validation:Required
	Source string `json:"source"`

	// +kubebuilder:validation:Required
	Spec SavedViewSpecPayload `json:"spec"`

	// +optional
	Name string `json:"name,omitempty"`
}

type SavedViewSpecPayload struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	DisplayName string `json:"displayName"`

	// +kubebuilder:validation:Enum=value;graph;table;list;trace
	// +kubebuilder:validation:Required
	PanelType string `json:"panelType"`

	// +kubebuilder:validation:Required
	Queries []SavedViewQuery `json:"queries"`

	// +kubebuilder:validation:Enum=scalar;time_series;raw;raw_stream;trace
	// +kubebuilder:validation:Required
	RequestType string `json:"requestType"`

	// +optional
	Display *SavedViewDisplay `json:"display,omitempty"`

	// +optional
	SelectedFields []SavedViewSelectField `json:"selectedFields,omitempty"`
}

// +kubebuilder:validation:XValidation:rule="self.type != 'builder_query' || !has(self.spec) || has(self.spec.signal)",message="type builder_query requires spec.signal"
// +kubebuilder:validation:XValidation:rule="self.type != 'builder_ai_query' || !has(self.spec) || has(self.spec.signal)",message="type builder_ai_query requires spec.signal"
type SavedViewQuery struct {
	// +kubebuilder:validation:Enum=builder_query;builder_ai_query;builder_formula;builder_trace_operator;promql;clickhouse_sql
	// +kubebuilder:validation:Required
	Type string `json:"type"`

	// +optional
	Spec *SavedViewQuerySpec `json:"spec,omitempty"`
}

type SavedViewQuerySpec struct {
	// +optional
	Aggregations []SavedViewAggregation `json:"aggregations,omitempty"`

	// +optional
	Cursor string `json:"cursor,omitempty"`

	// +optional
	Disabled bool `json:"disabled,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	Filter *SavedViewFilter `json:"filter,omitempty"`

	// +optional
	Functions []SavedViewFunction `json:"functions,omitempty"`

	// +optional
	GroupBy []SavedViewGroupBy `json:"groupBy,omitempty"`

	// +optional
	Having *SavedViewHaving `json:"having,omitempty"`

	// +optional
	Legend string `json:"legend,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *SavedViewLimitBy `json:"limitBy,omitempty"`

	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	Offset int64 `json:"offset,omitempty"`

	// +optional
	Order []SavedViewOrder `json:"order,omitempty"`

	// +optional
	Query string `json:"query,omitempty"`

	// +optional
	ReturnSpansFrom string `json:"returnSpansFrom,omitempty"`

	// +optional
	SecondaryAggregations []SavedViewSecondaryAggregation `json:"secondaryAggregations,omitempty"`

	// +optional
	SelectFields []SavedViewSelectField `json:"selectFields,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +kubebuilder:validation:Enum=meter
	// +optional
	Source string `json:"source,omitempty"`

	// +optional
	Stats bool `json:"stats,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Step *apiextensionsv1.JSON `json:"step,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type SavedViewAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	ComparisonSpaceAggregationParam *SavedViewComparisonSpaceAggregationParam `json:"comparisonSpaceAggregationParam,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	MetricName string `json:"metricName,omitempty"`

	// +kubebuilder:validation:Enum=sum;count;avg;min;max;last;median
	// +optional
	ReduceTo string `json:"reduceTo,omitempty"`

	// +kubebuilder:validation:Enum=sum;avg;min;max;count;p50;p75;p90;p95;p99
	// +optional
	SpaceAggregation string `json:"spaceAggregation,omitempty"`

	// +kubebuilder:validation:Enum=delta;cumulative;unspecified
	// +optional
	Temporality string `json:"temporality,omitempty"`

	// +kubebuilder:validation:Enum=latest;sum;avg;min;max;count;count_distinct;rate;increase
	// +optional
	TimeAggregation string `json:"timeAggregation,omitempty"`
}

type SavedViewComparisonSpaceAggregationParam struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Operator string `json:"operator"`

	// +kubebuilder:validation:Required
	Threshold float64 `json:"threshold"`
}

type SavedViewFilter struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type SavedViewFunction struct {
	// +optional
	Args []SavedViewArg `json:"args,omitempty"`

	// +kubebuilder:validation:Enum=cutoffmin;cutoffmax;clampmin;clampmax;absolute;runningdiff;log2;log10;cumulativesum;ewma3;ewma5;ewma7;median3;median5;median7;timeshift;anomaly;fillzero
	// +optional
	Name string `json:"name,omitempty"`
}

type SavedViewArg struct {
	// +optional
	Name string `json:"name,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	Value *apiextensionsv1.JSON `json:"value,omitempty"`
}

type SavedViewGroupBy struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type SavedViewHaving struct {
	// +optional
	Expression string `json:"expression,omitempty"`
}

type SavedViewLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type SavedViewOrder struct {
	// +kubebuilder:validation:Enum=asc;desc
	// +optional
	Direction string `json:"direction,omitempty"`

	// +optional
	Key *SavedViewKey `json:"key,omitempty"`
}

type SavedViewKey struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type SavedViewSecondaryAggregation struct {
	// +optional
	Alias string `json:"alias,omitempty"`

	// +optional
	Expression string `json:"expression,omitempty"`

	// +optional
	GroupBy []SavedViewGroupBy `json:"groupBy,omitempty"`

	// +optional
	Limit int64 `json:"limit,omitempty"`

	// +optional
	LimitBy *SavedViewSecondaryAggregationLimitBy `json:"limitBy,omitempty"`

	// +optional
	Order []SavedViewOrder `json:"order,omitempty"`

	// +optional
	// +kubebuilder:pruning:PreserveUnknownFields
	StepInterval *apiextensionsv1.JSON `json:"stepInterval,omitempty"`
}

type SavedViewSecondaryAggregationLimitBy struct {
	// +optional
	Keys []string `json:"keys,omitempty"`

	// +optional
	Value string `json:"value,omitempty"`
}

type SavedViewSelectField struct {
	// +kubebuilder:validation:Required
	// +kubebuilder:validation:MinLength=1
	Name string `json:"name"`

	// +optional
	Description string `json:"description,omitempty"`

	// +kubebuilder:validation:Enum=metric;log;span;resource;attribute;body
	// +optional
	FieldContext string `json:"fieldContext,omitempty"`

	// +kubebuilder:validation:Enum=string;bool;float64;int64;number
	// +optional
	FieldDataType string `json:"fieldDataType,omitempty"`

	// +kubebuilder:validation:Enum=traces;logs;metrics
	// +optional
	Signal string `json:"signal,omitempty"`

	// +optional
	Unit string `json:"unit,omitempty"`
}

type SavedViewDisplay struct {
	// +optional
	Color string `json:"color,omitempty"`

	// +optional
	FontSize string `json:"fontSize,omitempty"`

	// +optional
	Format string `json:"format,omitempty"`

	// +optional
	MaxLines int64 `json:"maxLines,omitempty"`
}

// +kubebuilder:validation:MinProperties=1
// +kubebuilder:validation:MaxProperties=1
type SavedViewObjectTemplate struct {
	// +optional
	Spec *SavedViewObjectSpec `json:"spec,omitempty"`

	// +optional
	// +kubebuilder:validation:MinLength=1
	JSONSpec *string `json:"jsonSpec,omitempty"`
}

type SavedViewSpec struct {
	CoreSpec `json:",inline"`

	// +kubebuilder:validation:Required
	ObjectTemplate SavedViewObjectTemplate `json:"objectTemplate"`
}

type SavedViewStatus struct {
	CoreStatus `json:",inline"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="Ready",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="Reason",type=string,JSONPath=".status.conditions[?(@.type=='Ready')].reason"
// +kubebuilder:printcolumn:name="ID",type=string,JSONPath=".status.signozResource.id"
// +kubebuilder:printcolumn:name="Age",type=date,JSONPath=".metadata.creationTimestamp"

type SavedView struct {
	metav1.TypeMeta `json:",inline"`

	// +optional
	metav1.ObjectMeta `json:"metadata,omitzero"`

	// +required
	Spec SavedViewSpec `json:"spec"`

	// +optional
	Status SavedViewStatus `json:"status,omitzero"`
}

// +kubebuilder:object:root=true

type SavedViewList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitzero"`
	Items           []SavedView `json:"items"`
}

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypes(SchemeGroupVersion, &SavedView{}, &SavedViewList{})
		return nil
	})
}
