name: build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: signoz/primus.workflows/.github/workflows/go-build.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_VERSION: "1.26"
      GO_BUILD_CONTEXT: ./cmd
      GO_BUILD_FLAGS: "-ldflags='-X github.com/SigNoz/signoz-operator/internal/build.Version=$($MAKE info-version)'"
      DOCKER_BASE_IMAGES: '{"distroless":"gcr.io/distroless/static:latest"}'
      DOCKER_DOCKERFILE_PATH: Dockerfile.multi-arch
      DOCKER_MANIFEST: true
      DOCKER_PROVIDERS: dockerhub
      DOCKER_DOCKERHUB_TAG_LATEST: ${{ !contains(github.ref_name, '-rc.') }}
  dist:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: kustomize-cli
        run: |
          which kustomize
          kustomize version
      - name: dist
        run: |
          mkdir -p dist
          (cd config/operator && kustomize edit set image controller=signoz/signoz-operator:"${GITHUB_REF_NAME}")
          kustomize build config/default > dist/signoz-operator.yaml
          kustomize build config/crd > dist/signoz-operator.crds.yaml
      - name: release-upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF_NAME}" \
            dist/signoz-operator.yaml \
            dist/signoz-operator.crds.yaml \
            --clobber
