name: build

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: signoz/primus.workflows/.github/workflows/go-build.yaml@main
    secrets: inherit
    with:
      PRIMUS_REF: main
      GO_VERSION: "1.26"
      GO_BUILD_CONTEXT: ./cmd
      GO_BUILD_FLAGS: "-ldflags='-X github.com/SigNoz/signoz-operator/internal/build.Version=$($MAKE info-version)'"
      DOCKER_BASE_IMAGES: '{"distroless":"gcr.io/distroless/static:latest"}'
      DOCKER_DOCKERFILE_PATH: Dockerfile.multi-arch
      DOCKER_MANIFEST: true
      DOCKER_PROVIDERS: dockerhub
      DOCKER_DOCKERHUB_TAG_LATEST: ${{ !contains(github.ref_name, '-rc.') }}
  dist:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: kustomize-cli
        run: |
          which kustomize
          kustomize version
      - name: dist
        run: |
          mkdir -p dist
          (cd config/controller && kustomize edit set image controller=signoz/signoz-operator:"${GITHUB_REF_NAME}")
          kustomize build config/default > dist/signoz-operator.yaml
          kustomize build config/crd > dist/signoz-operator.crds.yaml
      - name: release-upload
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${GITHUB_REF_NAME}" \
            dist/signoz-operator.yaml \
            dist/signoz-operator.crds.yaml \
            --clobber
  charts:
    needs: [build]
    if: ${{ !contains(github.ref_name, '-rc.') }}
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
    steps:
      - name: self-checkout
        uses: actions/checkout@v4
      - name: go-install
        uses: actions/setup-go@v5
        with:
          go-version: "1.26"
      - id: token
        name: github-token-gen
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PRIMUS_APP_ID }}
          private-key: ${{ secrets.PRIMUS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: charts
      - name: chart
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          GIT_USER: primus-bot[bot]
          GIT_EMAIL: 171087277+primus-bot[bot]@users.noreply.github.com
        run: ./hack/chart.sh "${GITHUB_REF_NAME}"
